# OpenAQ Data Crawling — 6 Hanoi Stations

Crawl hourly PM2.5, CO, NO2, O3, SO2 for 6 stations in Hanoi from the OpenAQ v3 API.  
Stations are read from `data/raw/DataAOD/Hanoi/Stations.xlsx`.  
Output CSVs are saved to the same folder.

## 1. Imports & Configuration

In [1]:
import os
import time
import random
from pathlib import Path

import pandas as pd
import requests

# API
OPENAQ_BASE_URL = "https://api.openaq.org/v3"
OPENAQ_API_KEY  = "8e8c3a875320048ecc88c70fcba8a72b10466adada7fb420c851038a59f3b987"
HEADERS         = {"X-API-Key": OPENAQ_API_KEY}

# Paths
PROJECT_ROOT  = Path("D:/Bussiness_plan/Multimodal_PM25")
STATIONS_FILE = PROJECT_ROOT / "data/raw/DataAOD/Hanoi/Stations.xlsx"
OUTPUT_DIR    = PROJECT_ROOT / "data/raw/DataAOD/Hanoi"
OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

# Crawl settings
GLOBAL_START_DATE = "2021-01-01"
GLOBAL_END_DATE   = "2026-05-15"
LIMIT             = 1000
WINDOW_DAYS       = 14     # 14-day windows to avoid 408 timeouts

TARGET_PARAMETERS = {
    "co":   "CO mass µg/m³",
    "no2":  "NO₂ mass µg/m³",
    "o3":   "O₃ mass µg/m³",
    "pm25": "PM2.5 µg/m³",
    "so2":  "SO₂ mass µg/m³",
}

print("Config loaded.")
print(f"  Output dir : {OUTPUT_DIR}")
print(f"  Date range : {GLOBAL_START_DATE}  →  {GLOBAL_END_DATE}")

Config loaded.
  Output dir : D:\Bussiness_plan\Multimodal_PM25\data\raw\DataAOD\Hanoi
  Date range : 2021-01-01  →  2026-05-15

## 2. Helper Functions

In [2]:
def request_json(url, params=None, timeout=60, max_retries=8):
    last_exc = None
    for attempt in range(max_retries):
        try:
            resp = requests.get(url, headers=HEADERS, params=params, timeout=timeout)

            if resp.status_code == 429:
                raw_reset = resp.headers.get("x-ratelimit-reset", "")
                try:
                    reset_val = float(raw_reset)
                    wait_s = max(reset_val - time.time(), 1) if reset_val > 1e9 else max(reset_val, 5)
                except (ValueError, TypeError):
                    wait_s = 60
                sleep_s = wait_s + random.uniform(2, 5)
                print(f"  429 rate-limit → sleep {sleep_s:.1f}s (attempt {attempt+1}/{max_retries})")
                time.sleep(sleep_s)
                continue

            if resp.status_code in {408, 500, 502, 503, 504}:
                sleep_s = min(120, 2 ** attempt + random.uniform(1, 3))
                print(f"  {resp.status_code} server error → retry in {sleep_s:.1f}s")
                time.sleep(sleep_s)
                continue

            resp.raise_for_status()
            return resp.json()

        except requests.RequestException as e:
            last_exc = e
            if attempt == max_retries - 1:
                raise
            sleep_s = min(120, 2 ** attempt + random.uniform(1, 3))
            print(f"  Network error: {e} → retry in {sleep_s:.1f}s")
            time.sleep(sleep_s)

    raise RuntimeError(
        f"Exhausted {max_retries} retries for {url}. "
        f"Last error: {last_exc}. "
        "Likely persistent 429/408 — wait a few minutes then re-run."
    )


def get_location_metadata(location_id: int) -> dict:
    payload = request_json(f"{OPENAQ_BASE_URL}/locations/{location_id}")
    results = payload.get("results", [])
    if not results:
        raise ValueError(f"Location {location_id} not found.")
    loc    = results[0]
    coords = loc.get("coordinates") or {}
    return {
        "location_id":   loc.get("id"),
        "location_name": loc.get("name"),
        "timezone":      loc.get("timezone"),
        "latitude":      coords.get("latitude"),
        "longitude":     coords.get("longitude"),
    }


def get_location_sensors(location_id: int) -> list:
    all_rows, page = [], 1
    while True:
        payload = request_json(
            f"{OPENAQ_BASE_URL}/locations/{location_id}/sensors",
            params={"limit": 1000, "page": page},
        )
        rows  = payload.get("results", [])
        found = int((payload.get("meta") or {}).get("found") or 0)
        all_rows.extend(rows)
        if not rows or page * 1000 >= found:
            break
        page += 1
    return all_rows


def build_sensor_inventory(location_id: int) -> pd.DataFrame:
    sensors = get_location_sensors(location_id)
    rows = []
    for s in sensors:
        p     = s.get("parameter") or {}
        pname = str(p.get("name", "")).lower()
        units = p.get("units")
        if pname not in TARGET_PARAMETERS or units != "µg/m³":
            continue
        dt_first = (s.get("datetimeFirst") or {}).get("utc")
        dt_last  = (s.get("datetimeLast")  or {}).get("utc")
        if not dt_first or not dt_last:
            continue
        rows.append({
            "sensor_id":         s.get("id"),
            "parameter_name":    pname,
            "datetimeFirst_utc": dt_first,
            "datetimeLast_utc":  dt_last,
        })
    df = pd.DataFrame(rows)
    if not df.empty:
        df = df.sort_values(["parameter_name", "sensor_id"]).reset_index(drop=True)
    return df


def split_windows(start_ts, end_ts, window_days=14):
    start_ts = pd.Timestamp(start_ts)
    end_ts   = pd.Timestamp(end_ts)
    windows, cur = [], start_ts
    step = pd.Timedelta(days=window_days)
    while cur <= end_ts:
        nxt = min(cur + step, end_ts)
        windows.append((cur, nxt))
        cur = nxt + pd.Timedelta(seconds=1)
    return windows


def fetch_sensor_hours(sensor_id: int, start_ts, end_ts) -> list:
    start_str = pd.Timestamp(start_ts).strftime("%Y-%m-%dT%H:%M:%SZ")
    end_str   = pd.Timestamp(end_ts).strftime("%Y-%m-%dT%H:%M:%SZ")
    all_results, page = [], 1
    while True:
        payload = request_json(
            f"{OPENAQ_BASE_URL}/sensors/{sensor_id}/hours",
            params={"datetime_from": start_str, "datetime_to": end_str,
                    "limit": LIMIT, "page": page},
        )
        results = payload.get("results", [])
        if not results:
            break
        all_results.extend(results)
        found = int((payload.get("meta") or {}).get("found") or 0)
        if page * LIMIT >= found:
            break
        page += 1
    return all_results


def extract_rows(results, parameter_name: str) -> list:
    rows = []
    for r in results:
        dt_to   = (r.get("period") or {}).get("datetimeTo") or {}
        summary = r.get("summary") or {}
        rows.append({
            "datetime_utc":   dt_to.get("utc"),
            "parameter_name": parameter_name,
            "value":          summary.get("avg"),
        })
    return rows


print("All helpers defined.")

All helpers defined.

## 3. Load Stations

In [3]:
df_raw = pd.read_excel(STATIONS_FILE)
df_raw.columns = [str(c).strip() for c in df_raw.columns]

df_stations = pd.DataFrame({
    "Location_id":   df_raw["Location"].astype(int),
    "Location_name": df_raw["Name"].str.strip(),
    "Start Date":    pd.Timestamp(GLOBAL_START_DATE),
    "End Date":      pd.Timestamp(GLOBAL_END_DATE),
})

print(f"Loaded {len(df_stations)} stations:")
display(df_stations)

Loaded 34 stations:

,Location_id,Location_name,Start Date,End Date
0,18,SPARTAN - Vietnam Acad. Sci.,2021-01-01,2026-05-15
1,2539,US Diplomatic Post: Hanoi,2021-01-01,2026-05-15
2,7441,Hanoi,2021-01-01,2026-05-15
3,307169,nồng độ pm,2021-01-01,2026-05-15
4,1285357,SPARTAN - Vietnam Acad. Sci.,2021-01-01,2026-05-15
5,2161290,An Khánh,2021-01-01,2026-05-15
6,2161291,Cầu Diễn,2021-01-01,2026-05-15
7,2161292,"Số 46, phố Lưu Quang Vũ",2021-01-01,2026-05-15
8,2161293,Chúc Sơn,2021-01-01,2026-05-15
9,2161294,Cung thiếu nhi,2021-01-01,2026-05-15
10,2161295,Đầm Trấu,2021-01-01,2026-05-15
11,2161296,Đào Duy Từ,2021-01-01,2026-05-15
12,2161298,Đông Kinh Nghĩa Thục,2021-01-01,2026-05-15
13,2161299,Hàng Đậu,2021-01-01,2026-05-15
14,2161300,Hoàn Kiếm,2021-01-01,2026-05-15
15,2161301,Khương Trung,2021-01-01,2026-05-15
16,2161303,Kim Liên,2021-01-01,2026-05-15
17,2161304,Lê Trực,2021-01-01,2026-05-15
18,2161306,Minh Khai - Bắc Từ Liêm,2021-01-01,2026-05-15
19,2161307,Mỹ Đình,2021-01-01,2026-05-15
20,2161308,Phạm Văn Đồng,2021-01-01,2026-05-15
21,2161309,Pháp Vân,2021-01-01,2026-05-15
22,2161313,Tân Mai,2021-01-01,2026-05-15
23,2161314,Tây Hồ Tây,2021-01-01,2026-05-15
24,2161315,Tây Mỗ,2021-01-01,2026-05-15
25,2161316,Thành Công,2021-01-01,2026-05-15
26,2161318,Tứ Liên,2021-01-01,2026-05-15
27,2161320,Vân Hà,2021-01-01,2026-05-15
28,2161321,Văn Quán,2021-01-01,2026-05-15
29,2161322,Võng La,2021-01-01,2026-05-15
30,4946811,556 Nguyễn Văn Cừ,2021-01-01,2026-05-15
31,4946812,Công viên Nhân Chính - Khuất Duy Tiến,2021-01-01,2026-05-15
32,4946813,Số 1 đường Giải Phóng - phường Bạch Mai - ĐHBK,2021-01-01,2026-05-15
33,6123215,OceanPark,2021-01-01,2026-05-15

## 4. Crawl All Stations

In [4]:
all_station_dfs = []

for _, station_row in df_stations.iterrows():
    loc_id   = int(station_row["Location_id"])
    loc_name = str(station_row["Location_name"]).strip()
    start_ts = pd.Timestamp(station_row["Start Date"]).tz_localize("UTC")
    end_ts   = pd.Timestamp(station_row["End Date"]).tz_localize("UTC")

    print(f"\n{'='*60}")
    print(f"Station {loc_id}: {loc_name}")
    print(f"  Range: {start_ts.date()}  →  {end_ts.date()}")

    # Metadata + sensor inventory
    try:
        meta      = get_location_metadata(loc_id)
        inventory = build_sensor_inventory(loc_id)
    except Exception as e:
        print(f"  [SKIP] metadata/sensor error: {e}")
        continue

    if inventory.empty:
        print("  [SKIP] No matching sensors found.")
        continue

    print(f"  Sensors: {len(inventory)}")

    # Fetch hourly data per sensor
    all_rows = []

    for s_row in inventory.itertuples(index=False):
        eff_start = max(start_ts, pd.Timestamp(s_row.datetimeFirst_utc).tz_convert("UTC"))
        eff_end   = min(end_ts,   pd.Timestamp(s_row.datetimeLast_utc).tz_convert("UTC"))
        if eff_start > eff_end:
            continue

        windows = split_windows(eff_start, eff_end, window_days=WINDOW_DAYS)
        print(f"  {s_row.parameter_name} | sensor={s_row.sensor_id} | {len(windows)} windows")

        for i, (w_start, w_end) in enumerate(windows, start=1):
            print(f"    [{i:03d}/{len(windows)}] {w_start.date()} → {w_end.date()}", end="  ")
            try:
                results = fetch_sensor_hours(s_row.sensor_id, w_start, w_end)
                rows    = extract_rows(results, s_row.parameter_name)
                all_rows.extend(rows)
                print(f"({len(rows)} records)")
            except Exception as e:
                print(f"[ERROR: {e}] — skipped")
            time.sleep(random.uniform(0.8, 1.5))

    if not all_rows:
        print("  [SKIP] No data fetched.")
        continue

    # Aggregate + pivot wide
    df_r = pd.DataFrame(all_rows)
    df_r["datetime_utc"]   = pd.to_datetime(df_r["datetime_utc"], utc=True, errors="coerce")
    df_r["parameter_name"] = df_r["parameter_name"].str.lower()
    df_r = df_r.dropna(subset=["datetime_utc"])

    df_agg = df_r.groupby(["datetime_utc", "parameter_name"], as_index=False)["value"].mean()

    final_df = (
        df_agg
        .pivot(index="datetime_utc", columns="parameter_name", values="value")
        .reset_index()
        .rename(columns=TARGET_PARAMETERS)
    )

    final_df["location_id"]   = meta["location_id"]
    final_df["location_name"] = meta["location_name"]
    final_df["latitude"]      = meta["latitude"]
    final_df["longitude"]     = meta["longitude"]

    col_order = [
        "datetime_utc", "location_id", "location_name", "latitude", "longitude",
        "CO mass µg/m³", "NO₂ mass µg/m³", "O₃ mass µg/m³", "PM2.5 µg/m³", "SO₂ mass µg/m³",
    ]
    for c in col_order:
        if c not in final_df.columns:
            final_df[c] = pd.NA
    final_df = final_df[col_order].sort_values("datetime_utc").reset_index(drop=True)

    # Save per-station CSV
    safe = loc_name.replace("/", "_").replace("\\", "_").replace(",", "").replace(".", "").strip()
    out_csv = OUTPUT_DIR / f"{loc_id}_{safe}.csv"
    final_df.to_csv(out_csv, index=False, encoding="utf-8-sig")
    print(f"  Saved: {out_csv.name}  shape={final_df.shape}")
    print(f"  PM2.5 rows: {final_df['PM2.5 µg/m³'].notna().sum()}")

    all_station_dfs.append(final_df)
    time.sleep(3)

# Combine all stations
print(f"\n{'='*60}")
if all_station_dfs:
    df_all = (
        pd.concat(all_station_dfs, ignore_index=True)
        .sort_values(["location_id", "datetime_utc"])
        .reset_index(drop=True)
    )
    out_all = OUTPUT_DIR / "all_stations_crawled.csv"
    df_all.to_csv(out_all, index=False, encoding="utf-8-sig")
    print(f"Combined: {out_all.name}  shape={df_all.shape}")
    display(
        df_all.groupby("location_id").agg(
            name       =("location_name", "first"),
            rows       =("datetime_utc",  "count"),
            pm25_valid =(("PM2.5 µg/m³"), lambda x: x.notna().sum()),
            start      =("datetime_utc",  "min"),
            end        =("datetime_utc",  "max"),
        )
    )
    display(df_all.head(10))
else:
    print("No data collected.")

============================================================
Station 18: SPARTAN - Vietnam Acad. Sci.
  Range: 2021-01-01  →  2026-05-15

  [SKIP] No matching sensors found.

============================================================
Station 2539: US Diplomatic Post: Hanoi
  Range: 2021-01-01  →  2026-05-15

  Sensors: 1
  [SKIP] No data fetched.

============================================================
Station 7441: Hanoi
  Range: 2021-01-01  →  2026-05-15

  Sensors: 1
  pm25 | sensor=21632 | 112 windows
    [001/112] 2021-01-01 → 2021-01-15

(312 records)

    [002/112] 2021-01-15 → 2021-01-29

(336 records)

    [003/112] 2021-01-29 → 2021-02-12

(312 records)

    [004/112] 2021-02-12 → 2021-02-26

(296 records)

    [005/112] 2021-02-26 → 2021-03-12

(285 records)

    [006/112] 2021-03-12 → 2021-03-26

(336 records)

    [007/112] 2021-03-26 → 2021-04-09

(312 records)

    [008/112] 2021-04-09 → 2021-04-23

(332 records)

    [009/112] 2021-04-23 → 2021-05-07

(257 records)

    [010/112] 2021-05-07 → 2021-05-21

(336 records)

    [011/112] 2021-05-21 → 2021-06-04

(232 records)

    [012/112] 2021-06-04 → 2021-06-18

(297 records)

    [013/112] 2021-06-18 → 2021-07-02

(312 records)

    [014/112] 2021-07-02 → 2021-07-16

(279 records)

    [015/112] 2021-07-16 → 2021-07-30

(224 records)

    [016/112] 2021-07-30 → 2021-08-13

(219 records)

    [017/112] 2021-08-13 → 2021-08-27

(330 records)

    [018/112] 2021-08-27 → 2021-09-10

(312 records)

    [019/112] 2021-09-10 → 2021-09-24

(336 records)

    [020/112] 2021-09-24 → 2021-10-08

(312 records)

    [021/112] 2021-10-08 → 2021-10-22

(336 records)

    [022/112] 2021-10-22 → 2021-11-05

(312 records)

    [023/112] 2021-11-05 → 2021-11-19

(336 records)

    [024/112] 2021-11-19 → 2021-12-03

(312 records)

    [025/112] 2021-12-03 → 2021-12-17

(336 records)

    [026/112] 2021-12-17 → 2021-12-31

(312 records)

    [027/112] 2021-12-31 → 2022-01-14

(336 records)

    [028/112] 2022-01-14 → 2022-01-28

(313 records)

    [029/112] 2022-01-28 → 2022-02-11

(335 records)

    [030/112] 2022-02-11 → 2022-02-25

(336 records)

    [031/112] 2022-02-25 → 2022-03-11

(312 records)

    [032/112] 2022-03-11 → 2022-03-25

(304 records)

    [033/112] 2022-03-25 → 2022-04-08

(312 records)

    [034/112] 2022-04-08 → 2022-04-22

(336 records)

    [035/112] 2022-04-22 → 2022-05-06

(312 records)

    [036/112] 2022-05-06 → 2022-05-20

(336 records)

    [037/112] 2022-05-20 → 2022-06-03

(312 records)

    [038/112] 2022-06-03 → 2022-06-17

(336 records)

    [039/112] 2022-06-17 → 2022-07-01

(312 records)

    [040/112] 2022-07-01 → 2022-07-15

(336 records)

    [041/112] 2022-07-15 → 2022-07-29

(312 records)

    [042/112] 2022-07-29 → 2022-08-12

(336 records)

    [043/112] 2022-08-12 → 2022-08-26

(313 records)

    [044/112] 2022-08-26 → 2022-09-09

(335 records)

    [045/112] 2022-09-09 → 2022-09-23

(336 records)

    [046/112] 2022-09-23 → 2022-10-07

(312 records)

    [047/112] 2022-10-07 → 2022-10-21

(336 records)

    [048/112] 2022-10-21 → 2022-11-04

(312 records)

    [049/112] 2022-11-04 → 2022-11-18

(336 records)

    [050/112] 2022-11-18 → 2022-12-02

(312 records)

    [051/112] 2022-12-02 → 2022-12-16

(336 records)

    [052/112] 2022-12-16 → 2022-12-30

(312 records)

    [053/112] 2022-12-30 → 2023-01-13

(307 records)

    [054/112] 2023-01-13 → 2023-01-27

(239 records)

    [055/112] 2023-01-27 → 2023-02-10

(145 records)

    [056/112] 2023-02-10 → 2023-02-24

(48 records)

    [057/112] 2023-02-24 → 2023-03-10

(0 records)

    [058/112] 2023-03-10 → 2023-03-24

(88 records)

    [059/112] 2023-03-24 → 2023-04-07

(335 records)

    [060/112] 2023-04-07 → 2023-04-21

(336 records)

    [061/112] 2023-04-21 → 2023-05-05

(281 records)

    [062/112] 2023-05-05 → 2023-05-19

(333 records)

    [063/112] 2023-05-19 → 2023-06-02

(336 records)

    [064/112] 2023-06-02 → 2023-06-16

(336 records)

    [065/112] 2023-06-16 → 2023-06-30

(336 records)

    [066/112] 2023-06-30 → 2023-07-14

(334 records)

    [067/112] 2023-07-14 → 2023-07-28

(317 records)

    [068/112] 2023-07-28 → 2023-08-11

(336 records)

    [069/112] 2023-08-11 → 2023-08-25

(335 records)

    [070/112] 2023-08-25 → 2023-09-08

(336 records)

    [071/112] 2023-09-08 → 2023-09-22

(336 records)

    [072/112] 2023-09-22 → 2023-10-06

(336 records)

    [073/112] 2023-10-06 → 2023-10-20

(334 records)

    [074/112] 2023-10-20 → 2023-11-03

(334 records)

    [075/112] 2023-11-03 → 2023-11-17

(103 records)

    [076/112] 2023-11-17 → 2023-12-01

(0 records)

    [077/112] 2023-12-01 → 2023-12-15

(171 records)

    [078/112] 2023-12-15 → 2023-12-29

(285 records)

    [079/112] 2023-12-29 → 2024-01-12

(233 records)

    [080/112] 2024-01-12 → 2024-01-26

(332 records)

    [081/112] 2024-01-26 → 2024-02-09

(313 records)

    [082/112] 2024-02-09 → 2024-02-23

(335 records)

    [083/112] 2024-02-23 → 2024-03-08

(330 records)

    [084/112] 2024-03-08 → 2024-03-22

(326 records)

    [085/112] 2024-03-22 → 2024-04-05

(336 records)

    [086/112] 2024-04-05 → 2024-04-19

(336 records)

    [087/112] 2024-04-19 → 2024-05-03

(336 records)

    [088/112] 2024-05-03 → 2024-05-17

(336 records)

    [089/112] 2024-05-17 → 2024-05-31

(336 records)

    [090/112] 2024-05-31 → 2024-06-14

(336 records)

    [091/112] 2024-06-14 → 2024-06-28

(336 records)

    [092/112] 2024-06-28 → 2024-07-12

(336 records)

    [093/112] 2024-07-12 → 2024-07-26

(336 records)

    [094/112] 2024-07-26 → 2024-08-09

(336 records)

    [095/112] 2024-08-09 → 2024-08-23

(336 records)

    [096/112] 2024-08-23 → 2024-09-06

(336 records)

    [097/112] 2024-09-06 → 2024-09-20

(336 records)

    [098/112] 2024-09-20 → 2024-10-04

(336 records)

    [099/112] 2024-10-04 → 2024-10-18

(336 records)

    [100/112] 2024-10-18 → 2024-11-01

(336 records)

    [101/112] 2024-11-01 → 2024-11-15

(336 records)

    [102/112] 2024-11-15 → 2024-11-29

(336 records)

    [103/112] 2024-11-29 → 2024-12-13

(336 records)

    [104/112] 2024-12-13 → 2024-12-27

(336 records)

    [105/112] 2024-12-27 → 2025-01-10

(336 records)

    [106/112] 2025-01-10 → 2025-01-24

(336 records)

    [107/112] 2025-01-24 → 2025-02-07

(336 records)

    [108/112] 2025-02-07 → 2025-02-21

(336 records)

    [109/112] 2025-02-21 → 2025-03-07

(336 records)

    [110/112] 2025-03-07 → 2025-03-21

(309 records)

    [111/112] 2025-03-21 → 2025-04-04

(334 records)

    [112/112] 2025-04-04 → 2025-04-09

(135 records)

  Saved: 7441_Hanoi.csv  shape=(34051, 10)
  PM2.5 rows: 30157

============================================================
Station 307169: nồng độ pm
  Range: 2021-01-01  →  2026-05-15

  [SKIP] No matching sensors found.

============================================================
Station 1285357: SPARTAN - Vietnam Acad. Sci.
  Range: 2021-01-01  →  2026-05-15

  Sensors: 1
  [SKIP] No data fetched.

============================================================
Station 2161290: An Khánh
  Range: 2021-01-01  →  2026-05-15

  Sensors: 3
  co | sensor=7771981 | 36 windows
    [001/36] 2024-01-29 → 2024-02-12

(266 records)

    [002/36] 2024-02-12 → 2024-02-26

(321 records)

    [003/36] 2024-02-26 → 2024-03-11

(231 records)

    [004/36] 2024-03-11 → 2024-03-25

(230 records)

    [005/36] 2024-03-25 → 2024-04-08

(323 records)

    [006/36] 2024-04-08 → 2024-04-22

(267 records)

    [007/36] 2024-04-22 → 2024-05-06

(214 records)

    [008/36] 2024-05-06 → 2024-05-20

(323 records)

    [009/36] 2024-05-20 → 2024-06-03

(178 records)

    [010/36] 2024-06-03 → 2024-06-17

(336 records)

    [011/36] 2024-06-17 → 2024-07-01

(331 records)

    [012/36] 2024-07-01 → 2024-07-15

(19 records)

    [013/36] 2024-07-15 → 2024-07-29

(0 records)

    [014/36] 2024-07-29 → 2024-08-12

(0 records)

    [015/36] 2024-08-12 → 2024-08-26

(0 records)

    [016/36] 2024-08-26 → 2024-09-09

(17 records)

    [017/36] 2024-09-09 → 2024-09-23

(332 records)

    [018/36] 2024-09-23 → 2024-10-07

(333 records)

    [019/36] 2024-10-07 → 2024-10-21

(329 records)

    [020/36] 2024-10-21 → 2024-11-04

(331 records)

    [021/36] 2024-11-04 → 2024-11-18

(300 records)

    [022/36] 2024-11-18 → 2024-12-02

(332 records)

    [023/36] 2024-12-02 → 2024-12-16

(332 records)

    [024/36] 2024-12-16 → 2024-12-30

(333 records)

    [025/36] 2024-12-30 → 2025-01-13

(325 records)

    [026/36] 2025-01-13 → 2025-01-27

(318 records)

    [027/36] 2025-01-27 → 2025-02-10

(336 records)

    [028/36] 2025-02-10 → 2025-02-24

(336 records)

    [029/36] 2025-02-24 → 2025-03-10

(336 records)

    [030/36] 2025-03-10 → 2025-03-24

(336 records)

    [031/36] 2025-03-24 → 2025-04-07

(334 records)

    [032/36] 2025-04-07 → 2025-04-21

(336 records)

    [033/36] 2025-04-21 → 2025-05-05

(234 records)

    [034/36] 2025-05-05 → 2025-05-19

(336 records)

    [035/36] 2025-05-19 → 2025-06-02

(329 records)

    [036/36] 2025-06-02 → 2025-06-10

(189 records)

  no2 | sensor=7772033 | 36 windows
    [001/36] 2024-01-29 → 2024-02-12

(266 records)

    [002/36] 2024-02-12 → 2024-02-26

(321 records)

    [003/36] 2024-02-26 → 2024-03-11

(231 records)

    [004/36] 2024-03-11 → 2024-03-25

(229 records)

    [005/36] 2024-03-25 → 2024-04-08

(324 records)

    [006/36] 2024-04-08 → 2024-04-22

(267 records)

    [007/36] 2024-04-22 → 2024-05-06

(214 records)

    [008/36] 2024-05-06 → 2024-05-20

(323 records)

    [009/36] 2024-05-20 → 2024-06-03

(178 records)

    [010/36] 2024-06-03 → 2024-06-17

(336 records)

    [011/36] 2024-06-17 → 2024-07-01

(332 records)

    [012/36] 2024-07-01 → 2024-07-15

(19 records)

    [013/36] 2024-07-15 → 2024-07-29

(0 records)

    [014/36] 2024-07-29 → 2024-08-12

(0 records)

    [015/36] 2024-08-12 → 2024-08-26

(0 records)

    [016/36] 2024-08-26 → 2024-09-09

(17 records)

    [017/36] 2024-09-09 → 2024-09-23

(332 records)

    [018/36] 2024-09-23 → 2024-10-07

(333 records)

    [019/36] 2024-10-07 → 2024-10-21

(326 records)

    [020/36] 2024-10-21 → 2024-11-04

(331 records)

    [021/36] 2024-11-04 → 2024-11-18

(300 records)

    [022/36] 2024-11-18 → 2024-12-02

(332 records)

    [023/36] 2024-12-02 → 2024-12-16

(335 records)

    [024/36] 2024-12-16 → 2024-12-30

(333 records)

    [025/36] 2024-12-30 → 2025-01-13

(325 records)

    [026/36] 2025-01-13 → 2025-01-27

(318 records)

    [027/36] 2025-01-27 → 2025-02-10

(336 records)

    [028/36] 2025-02-10 → 2025-02-24

(336 records)

    [029/36] 2025-02-24 → 2025-03-10

(336 records)

    [030/36] 2025-03-10 → 2025-03-24

(336 records)

    [031/36] 2025-03-24 → 2025-04-07

(334 records)

    [032/36] 2025-04-07 → 2025-04-21

(336 records)

    [033/36] 2025-04-21 → 2025-05-05

(234 records)

    [034/36] 2025-05-05 → 2025-05-19

(336 records)

    [035/36] 2025-05-19 → 2025-06-02

(329 records)

    [036/36] 2025-06-02 → 2025-06-10

(189 records)

  pm25 | sensor=7772012 | 36 windows
    [001/36] 2024-01-29 → 2024-02-12

(266 records)

    [002/36] 2024-02-12 → 2024-02-26

(321 records)

    [003/36] 2024-02-26 → 2024-03-11

(231 records)

    [004/36] 2024-03-11 → 2024-03-25

(230 records)

    [005/36] 2024-03-25 → 2024-04-08

(323 records)

    [006/36] 2024-04-08 → 2024-04-22

(268 records)

    [007/36] 2024-04-22 → 2024-05-06

(214 records)

    [008/36] 2024-05-06 → 2024-05-20

(323 records)

    [009/36] 2024-05-20 → 2024-06-03

(178 records)

    [010/36] 2024-06-03 → 2024-06-17

(336 records)

    [011/36] 2024-06-17 → 2024-07-01

(331 records)

    [012/36] 2024-07-01 → 2024-07-15

(19 records)

    [013/36] 2024-07-15 → 2024-07-29

(0 records)

    [014/36] 2024-07-29 → 2024-08-12

(0 records)

    [015/36] 2024-08-12 → 2024-08-26

(0 records)

    [016/36] 2024-08-26 → 2024-09-09

(17 records)

    [017/36] 2024-09-09 → 2024-09-23

(332 records)

    [018/36] 2024-09-23 → 2024-10-07

(333 records)

    [019/36] 2024-10-07 → 2024-10-21

(329 records)

    [020/36] 2024-10-21 → 2024-11-04

(331 records)

    [021/36] 2024-11-04 → 2024-11-18

(300 records)

    [022/36] 2024-11-18 → 2024-12-02

(332 records)

    [023/36] 2024-12-02 → 2024-12-16

(324 records)

    [024/36] 2024-12-16 → 2024-12-30

(333 records)

    [025/36] 2024-12-30 → 2025-01-13

(325 records)

    [026/36] 2025-01-13 → 2025-01-27

(318 records)

    [027/36] 2025-01-27 → 2025-02-10

(336 records)

    [028/36] 2025-02-10 → 2025-02-24

(336 records)

    [029/36] 2025-02-24 → 2025-03-10

(336 records)

    [030/36] 2025-03-10 → 2025-03-24

(336 records)

    [031/36] 2025-03-24 → 2025-04-07

(334 records)

    [032/36] 2025-04-07 → 2025-04-21

(336 records)

    [033/36] 2025-04-21 → 2025-05-05

(234 records)

    [034/36] 2025-05-05 → 2025-05-19

(336 records)

    [035/36] 2025-05-19 → 2025-06-02

(329 records)

    [036/36] 2025-06-02 → 2025-06-10

(189 records)

  Saved: 2161290_An Khánh.csv  shape=(9430, 10)
  PM2.5 rows: 9416

============================================================
Station 2161291: Cầu Diễn
  Range: 2021-01-01  →  2026-05-15

  Sensors: 3
  co | sensor=7772103 | 24 windows
    [001/24] 2024-01-22 → 2024-02-05

(2 records)

    [002/24] 2024-02-05 → 2024-02-19

(0 records)

    [003/24] 2024-02-19 → 2024-03-04

(0 records)

    [004/24] 2024-03-04 → 2024-03-18

(0 records)

    [005/24] 2024-03-18 → 2024-04-01

(0 records)

    [006/24] 2024-04-01 → 2024-04-15

(0 records)

    [007/24] 2024-04-15 → 2024-04-29

(0 records)

    [008/24] 2024-04-29 → 2024-05-13

(0 records)

    [009/24] 2024-05-13 → 2024-05-27

(0 records)

    [010/24] 2024-05-27 → 2024-06-10

(0 records)

    [011/24] 2024-06-10 → 2024-06-24

(0 records)

    [012/24] 2024-06-24 → 2024-07-08

(0 records)

    [013/24] 2024-07-08 → 2024-07-22

(0 records)

    [014/24] 2024-07-22 → 2024-08-05

(0 records)

    [015/24] 2024-08-05 → 2024-08-19

(0 records)

    [016/24] 2024-08-19 → 2024-09-02

(0 records)

    [017/24] 2024-09-02 → 2024-09-16

(0 records)

    [018/24] 2024-09-16 → 2024-09-30

(66 records)

    [019/24] 2024-09-30 → 2024-10-14

(168 records)

    [020/24] 2024-10-14 → 2024-10-28

(314 records)

    [021/24] 2024-10-28 → 2024-11-11

(299 records)

    [022/24] 2024-11-11 → 2024-11-25

(328 records)

    [023/24] 2024-11-25 → 2024-12-09

(286 records)

    [024/24] 2024-12-09 → 2024-12-11

(39 records)

  no2 | sensor=7771974 | 24 windows
    [001/24] 2024-01-22 → 2024-02-05

(2 records)

    [002/24] 2024-02-05 → 2024-02-19

(0 records)

    [003/24] 2024-02-19 → 2024-03-04

(0 records)

    [004/24] 2024-03-04 → 2024-03-18

(0 records)

    [005/24] 2024-03-18 → 2024-04-01

(0 records)

    [006/24] 2024-04-01 → 2024-04-15

(0 records)

    [007/24] 2024-04-15 → 2024-04-29

(0 records)

    [008/24] 2024-04-29 → 2024-05-13

(0 records)

    [009/24] 2024-05-13 → 2024-05-27

(0 records)

    [010/24] 2024-05-27 → 2024-06-10

(0 records)

    [011/24] 2024-06-10 → 2024-06-24

(0 records)

    [012/24] 2024-06-24 → 2024-07-08

(0 records)

    [013/24] 2024-07-08 → 2024-07-22

(0 records)

    [014/24] 2024-07-22 → 2024-08-05

(0 records)

    [015/24] 2024-08-05 → 2024-08-19

(0 records)

    [016/24] 2024-08-19 → 2024-09-02

(0 records)

    [017/24] 2024-09-02 → 2024-09-16

(1 records)

    [018/24] 2024-09-16 → 2024-09-30

(66 records)

    [019/24] 2024-09-30 → 2024-10-14

(169 records)

    [020/24] 2024-10-14 → 2024-10-28

(314 records)

    [021/24] 2024-10-28 → 2024-11-11

(299 records)

    [022/24] 2024-11-11 → 2024-11-25

(328 records)

    [023/24] 2024-11-25 → 2024-12-09

(286 records)

    [024/24] 2024-12-09 → 2024-12-11

(39 records)

  pm25 | sensor=7772023 | 24 windows
    [001/24] 2024-01-22 → 2024-02-05

(2 records)

    [002/24] 2024-02-05 → 2024-02-19

(0 records)

    [003/24] 2024-02-19 → 2024-03-04

(0 records)

    [004/24] 2024-03-04 → 2024-03-18

(0 records)

    [005/24] 2024-03-18 → 2024-04-01

(0 records)

    [006/24] 2024-04-01 → 2024-04-15

(0 records)

    [007/24] 2024-04-15 → 2024-04-29

(0 records)

    [008/24] 2024-04-29 → 2024-05-13

(0 records)

    [009/24] 2024-05-13 → 2024-05-27

(0 records)

    [010/24] 2024-05-27 → 2024-06-10

(0 records)

    [011/24] 2024-06-10 → 2024-06-24

(0 records)

    [012/24] 2024-06-24 → 2024-07-08

(0 records)

    [013/24] 2024-07-08 → 2024-07-22

(0 records)

    [014/24] 2024-07-22 → 2024-08-05

(0 records)

    [015/24] 2024-08-05 → 2024-08-19

(0 records)

    [016/24] 2024-08-19 → 2024-09-02

(0 records)

    [017/24] 2024-09-02 → 2024-09-16

(0 records)

    [018/24] 2024-09-16 → 2024-09-30

(64 records)

    [019/24] 2024-09-30 → 2024-10-14

(167 records)

    [020/24] 2024-10-14 → 2024-10-28

(313 records)

    [021/24] 2024-10-28 → 2024-11-11

(299 records)

    [022/24] 2024-11-11 → 2024-11-25

(327 records)

    [023/24] 2024-11-25 → 2024-12-09

(286 records)

    [024/24] 2024-12-09 → 2024-12-11

(39 records)

  Saved: 2161291_Cầu Diễn.csv  shape=(1504, 10)
  PM2.5 rows: 1497

============================================================
Station 2161292: Số 46, phố Lưu Quang Vũ
  Range: 2021-01-01  →  2026-05-15

  Sensors: 5
  co | sensor=7772024 | 60 windows
    [001/60] 2024-01-29 → 2024-02-12

(295 records)

    [002/60] 2024-02-12 → 2024-02-26

(334 records)

    [003/60] 2024-02-26 → 2024-03-11

(316 records)

    [004/60] 2024-03-11 → 2024-03-25

(217 records)

    [005/60] 2024-03-25 → 2024-04-08

(330 records)

    [006/60] 2024-04-08 → 2024-04-22

(279 records)

    [007/60] 2024-04-22 → 2024-05-06

(246 records)

    [008/60] 2024-05-06 → 2024-05-20

(328 records)

    [009/60] 2024-05-20 → 2024-06-03

(179 records)

    [010/60] 2024-06-03 → 2024-06-17

(336 records)

    [011/60] 2024-06-17 → 2024-07-01

(336 records)

    [012/60] 2024-07-01 → 2024-07-15

(335 records)

    [013/60] 2024-07-15 → 2024-07-29

(336 records)

    [014/60] 2024-07-29 → 2024-08-12

(326 records)

    [015/60] 2024-08-12 → 2024-08-26

(115 records)

    [016/60] 2024-08-26 → 2024-09-09

(127 records)

    [017/60] 2024-09-09 → 2024-09-23

(335 records)

    [018/60] 2024-09-23 → 2024-10-07

(334 records)

    [019/60] 2024-10-07 → 2024-10-21

(330 records)

    [020/60] 2024-10-21 → 2024-11-04

(332 records)

    [021/60] 2024-11-04 → 2024-11-18

(300 records)

    [022/60] 2024-11-18 → 2024-12-02

(330 records)

    [023/60] 2024-12-02 → 2024-12-16

(319 records)

    [024/60] 2024-12-16 → 2024-12-30

(212 records)

    [025/60] 2024-12-30 → 2025-01-13

(313 records)

    [026/60] 2025-01-13 → 2025-01-27

(39 records)

    [027/60] 2025-01-27 → 2025-02-10

(0 records)

    [028/60] 2025-02-10 → 2025-02-24

(302 records)

    [029/60] 2025-02-24 → 2025-03-10

(335 records)

    [030/60] 2025-03-10 → 2025-03-24

(73 records)

    [031/60] 2025-03-24 → 2025-04-07

(0 records)

    [032/60] 2025-04-07 → 2025-04-21

(0 records)

    [033/60] 2025-04-21 → 2025-05-05

(154 records)

    [034/60] 2025-05-05 → 2025-05-19

(335 records)

    [035/60] 2025-05-19 → 2025-06-02

(329 records)

    [036/60] 2025-06-02 → 2025-06-16

(321 records)

    [037/60] 2025-06-16 → 2025-06-30

(290 records)

    [038/60] 2025-06-30 → 2025-07-14

(318 records)

    [039/60] 2025-07-14 → 2025-07-28

(335 records)

    [040/60] 2025-07-28 → 2025-08-11

(263 records)

    [041/60] 2025-08-11 → 2025-08-25

(333 records)

    [042/60] 2025-08-25 → 2025-09-08

(335 records)

    [043/60] 2025-09-08 → 2025-09-22

(327 records)

    [044/60] 2025-09-22 → 2025-10-06

(336 records)

    [045/60] 2025-10-06 → 2025-10-20

(336 records)

    [046/60] 2025-10-20 → 2025-11-03

(335 records)

    [047/60] 2025-11-03 → 2025-11-17

(336 records)

    [048/60] 2025-11-17 → 2025-12-01

(237 records)

    [049/60] 2025-12-01 → 2025-12-15

(22 records)

    [050/60] 2025-12-15 → 2025-12-29

(279 records)

    [051/60] 2025-12-29 → 2026-01-12

(41 records)

    [052/60] 2026-01-12 → 2026-01-26

(195 records)

    [053/60] 2026-01-26 → 2026-02-09

(173 records)

    [054/60] 2026-02-09 → 2026-02-23

(209 records)

    [055/60] 2026-02-23 → 2026-03-09

(225 records)

    [056/60] 2026-03-09 → 2026-03-23

(195 records)

    [057/60] 2026-03-23 → 2026-04-06

(160 records)

    [058/60] 2026-04-06 → 2026-04-20

(186 records)

    [059/60] 2026-04-20 → 2026-05-04

(86 records)

    [060/60] 2026-05-04 → 2026-05-15

(161 records)

  no2 | sensor=7888636 | 59 windows
    [001/59] 2024-02-19 → 2024-03-04

(334 records)

    [002/59] 2024-03-04 → 2024-03-18

(201 records)

    [003/59] 2024-03-18 → 2024-04-01

(52 records)

    [004/59] 2024-04-01 → 2024-04-15

(129 records)

    [005/59] 2024-04-15 → 2024-04-29

(142 records)

    [006/59] 2024-04-29 → 2024-05-13

(336 records)

    [007/59] 2024-05-13 → 2024-05-27

(314 records)

    [008/59] 2024-05-27 → 2024-06-10

(193 records)

    [009/59] 2024-06-10 → 2024-06-24

(336 records)

    [010/59] 2024-06-24 → 2024-07-08

(335 records)

    [011/59] 2024-07-08 → 2024-07-22

(335 records)

    [012/59] 2024-07-22 → 2024-08-05

(336 records)

    [013/59] 2024-08-05 → 2024-08-19

(284 records)

    [014/59] 2024-08-19 → 2024-09-02

(60 records)

    [015/59] 2024-09-02 → 2024-09-16

(229 records)

    [016/59] 2024-09-16 → 2024-09-30

(336 records)

    [017/59] 2024-09-30 → 2024-10-14

(336 records)

    [018/59] 2024-10-14 → 2024-10-28

(289 records)

    [019/59] 2024-10-28 → 2024-11-11

(305 records)

    [020/59] 2024-11-11 → 2024-11-25

(327 records)

    [021/59] 2024-11-25 → 2024-12-09

(321 records)

    [022/59] 2024-12-09 → 2024-12-23

(335 records)

    [023/59] 2024-12-23 → 2025-01-06

(185 records)

    [024/59] 2025-01-06 → 2025-01-20

(326 records)

    [025/59] 2025-01-20 → 2025-02-03

(319 records)

    [026/59] 2025-02-03 → 2025-02-17

(334 records)

    [027/59] 2025-02-17 → 2025-03-03

(336 records)

    [028/59] 2025-03-03 → 2025-03-17

(335 records)

    [029/59] 2025-03-17 → 2025-03-31

(307 records)

    [030/59] 2025-03-31 → 2025-04-14

(336 records)

    [031/59] 2025-04-14 → 2025-04-28

(206 records)

    [032/59] 2025-04-28 → 2025-05-12

(0 records)

    [033/59] 2025-05-12 → 2025-05-26

(0 records)

    [034/59] 2025-05-26 → 2025-06-09

(0 records)

    [035/59] 2025-06-09 → 2025-06-23

(0 records)

    [036/59] 2025-06-23 → 2025-07-07

(0 records)

    [037/59] 2025-07-07 → 2025-07-21

(0 records)

    [038/59] 2025-07-21 → 2025-08-04

(0 records)

    [039/59] 2025-08-04 → 2025-08-18

(0 records)

    [040/59] 2025-08-18 → 2025-09-01

(0 records)

    [041/59] 2025-09-01 → 2025-09-15

(118 records)

    [042/59] 2025-09-15 → 2025-09-29

(92 records)

    [043/59] 2025-09-29 → 2025-10-13

(0 records)

    [044/59] 2025-10-13 → 2025-10-27

(0 records)

    [045/59] 2025-10-27 → 2025-11-10

(259 records)

    [046/59] 2025-11-10 → 2025-11-24

(336 records)

    [047/59] 2025-11-24 → 2025-12-08

(82 records)

    [048/59] 2025-12-08 → 2025-12-22

(0 records)

    [049/59] 2025-12-22 → 2026-01-05

(0 records)

    [050/59] 2026-01-05 → 2026-01-19

(144 records)

    [051/59] 2026-01-19 → 2026-02-02

(150 records)

    [052/59] 2026-02-02 → 2026-02-16

(205 records)

    [053/59] 2026-02-16 → 2026-03-02

(219 records)

    [054/59] 2026-03-02 → 2026-03-16

(219 records)

    [055/59] 2026-03-16 → 2026-03-30

(182 records)

    [056/59] 2026-03-30 → 2026-04-13

(152 records)

    [057/59] 2026-04-13 → 2026-04-27

(183 records)

    [058/59] 2026-04-27 → 2026-05-11

(107 records)

    [059/59] 2026-05-11 → 2026-05-15

(70 records)

  o3 | sensor=7772022 | 60 windows
    [001/60] 2024-01-29 → 2024-02-12

(295 records)

    [002/60] 2024-02-12 → 2024-02-26

(336 records)

    [003/60] 2024-02-26 → 2024-03-11

(316 records)

    [004/60] 2024-03-11 → 2024-03-25

(217 records)

    [005/60] 2024-03-25 → 2024-04-08

(332 records)

    [006/60] 2024-04-08 → 2024-04-22

(279 records)

    [007/60] 2024-04-22 → 2024-05-06

(246 records)

    [008/60] 2024-05-06 → 2024-05-20

(328 records)

    [009/60] 2024-05-20 → 2024-06-03

(179 records)

    [010/60] 2024-06-03 → 2024-06-17

(336 records)

    [011/60] 2024-06-17 → 2024-07-01

(336 records)

    [012/60] 2024-07-01 → 2024-07-15

(336 records)

    [013/60] 2024-07-15 → 2024-07-29

(336 records)

    [014/60] 2024-07-29 → 2024-08-12

(331 records)

    [015/60] 2024-08-12 → 2024-08-26

(115 records)

    [016/60] 2024-08-26 → 2024-09-09

(127 records)

    [017/60] 2024-09-09 → 2024-09-23

(335 records)

    [018/60] 2024-09-23 → 2024-10-07

(336 records)

    [019/60] 2024-10-07 → 2024-10-21

(239 records)

    [020/60] 2024-10-21 → 2024-11-04

(332 records)

    [021/60] 2024-11-04 → 2024-11-18

(128 records)

    [022/60] 2024-11-18 → 2024-12-02

(179 records)

    [023/60] 2024-12-02 → 2024-12-16

(321 records)

    [024/60] 2024-12-16 → 2024-12-30

(336 records)

    [025/60] 2024-12-30 → 2025-01-13

(328 records)

    [026/60] 2025-01-13 → 2025-01-27

(309 records)

    [027/60] 2025-01-27 → 2025-02-10

(334 records)

    [028/60] 2025-02-10 → 2025-02-24

(336 records)

    [029/60] 2025-02-24 → 2025-03-10

(335 records)

    [030/60] 2025-03-10 → 2025-03-24

(322 records)

    [031/60] 2025-03-24 → 2025-04-07

(0 records)

    [032/60] 2025-04-07 → 2025-04-21

(0 records)

    [033/60] 2025-04-21 → 2025-05-05

(0 records)

    [034/60] 2025-05-05 → 2025-05-19

(0 records)

    [035/60] 2025-05-19 → 2025-06-02

(0 records)

    [036/60] 2025-06-02 → 2025-06-16

(0 records)

    [037/60] 2025-06-16 → 2025-06-30

(0 records)

    [038/60] 2025-06-30 → 2025-07-14

(0 records)

    [039/60] 2025-07-14 → 2025-07-28

(0 records)

    [040/60] 2025-07-28 → 2025-08-11

(0 records)

    [041/60] 2025-08-11 → 2025-08-25

(0 records)

    [042/60] 2025-08-25 → 2025-09-08

(0 records)

    [043/60] 2025-09-08 → 2025-09-22

(292 records)

    [044/60] 2025-09-22 → 2025-10-06

(336 records)

    [045/60] 2025-10-06 → 2025-10-20

(336 records)

    [046/60] 2025-10-20 → 2025-11-03

(336 records)

    [047/60] 2025-11-03 → 2025-11-17

(336 records)

    [048/60] 2025-11-17 → 2025-12-01

(237 records)

    [049/60] 2025-12-01 → 2025-12-15

(22 records)

    [050/60] 2025-12-15 → 2025-12-29

(279 records)

    [051/60] 2025-12-29 → 2026-01-12

(41 records)

    [052/60] 2026-01-12 → 2026-01-26

(195 records)

    [053/60] 2026-01-26 → 2026-02-09

(173 records)

    [054/60] 2026-02-09 → 2026-02-23

(209 records)

    [055/60] 2026-02-23 → 2026-03-09

(225 records)

    [056/60] 2026-03-09 → 2026-03-23

(195 records)

    [057/60] 2026-03-23 → 2026-04-06

(160 records)

    [058/60] 2026-04-06 → 2026-04-20

(186 records)

    [059/60] 2026-04-20 → 2026-05-04

(86 records)

    [060/60] 2026-05-04 → 2026-05-15

(161 records)

  pm25 | sensor=7772032 | 60 windows
    [001/60] 2024-01-29 → 2024-02-12

(295 records)

    [002/60] 2024-02-12 → 2024-02-26

(336 records)

    [003/60] 2024-02-26 → 2024-03-11

(316 records)

    [004/60] 2024-03-11 → 2024-03-25

(210 records)

    [005/60] 2024-03-25 → 2024-04-08

(330 records)

    [006/60] 2024-04-08 → 2024-04-22

(279 records)

    [007/60] 2024-04-22 → 2024-05-06

(245 records)

    [008/60] 2024-05-06 → 2024-05-20

(311 records)

    [009/60] 2024-05-20 → 2024-06-03

(176 records)

    [010/60] 2024-06-03 → 2024-06-17

(332 records)

    [011/60] 2024-06-17 → 2024-07-01

(334 records)

    [012/60] 2024-07-01 → 2024-07-15

(336 records)

    [013/60] 2024-07-15 → 2024-07-29

(331 records)

    [014/60] 2024-07-29 → 2024-08-12

(329 records)

    [015/60] 2024-08-12 → 2024-08-26

(115 records)

    [016/60] 2024-08-26 → 2024-09-09

(128 records)

    [017/60] 2024-09-09 → 2024-09-23

(335 records)

    [018/60] 2024-09-23 → 2024-10-07

(336 records)

    [019/60] 2024-10-07 → 2024-10-21

(330 records)

    [020/60] 2024-10-21 → 2024-11-04

(332 records)

    [021/60] 2024-11-04 → 2024-11-18

(300 records)

    [022/60] 2024-11-18 → 2024-12-02

(336 records)

    [023/60] 2024-12-02 → 2024-12-16

(321 records)

    [024/60] 2024-12-16 → 2024-12-30

(336 records)

    [025/60] 2024-12-30 → 2025-01-13

(328 records)

    [026/60] 2025-01-13 → 2025-01-27

(301 records)

    [027/60] 2025-01-27 → 2025-02-10

(334 records)

    [028/60] 2025-02-10 → 2025-02-24

(336 records)

    [029/60] 2025-02-24 → 2025-03-10

(335 records)

    [030/60] 2025-03-10 → 2025-03-24

(321 records)

    [031/60] 2025-03-24 → 2025-04-07

(322 records)

    [032/60] 2025-04-07 → 2025-04-21

(336 records)

    [033/60] 2025-04-21 → 2025-05-05

(237 records)

    [034/60] 2025-05-05 → 2025-05-19

(335 records)

    [035/60] 2025-05-19 → 2025-06-02

(326 records)

    [036/60] 2025-06-02 → 2025-06-16

(322 records)

    [037/60] 2025-06-16 → 2025-06-30

(290 records)

    [038/60] 2025-06-30 → 2025-07-14

(317 records)

    [039/60] 2025-07-14 → 2025-07-28

(335 records)

    [040/60] 2025-07-28 → 2025-08-11

(177 records)

    [041/60] 2025-08-11 → 2025-08-25

(333 records)

    [042/60] 2025-08-25 → 2025-09-08

(336 records)

    [043/60] 2025-09-08 → 2025-09-22

(328 records)

    [044/60] 2025-09-22 → 2025-10-06

(336 records)

    [045/60] 2025-10-06 → 2025-10-20

(336 records)

    [046/60] 2025-10-20 → 2025-11-03

(336 records)

    [047/60] 2025-11-03 → 2025-11-17

(336 records)

    [048/60] 2025-11-17 → 2025-12-01

(93 records)

    [049/60] 2025-12-01 → 2025-12-15

(0 records)

    [050/60] 2025-12-15 → 2025-12-29

(19 records)

    [051/60] 2025-12-29 → 2026-01-12

(41 records)

    [052/60] 2026-01-12 → 2026-01-26

(194 records)

    [053/60] 2026-01-26 → 2026-02-09

(173 records)

    [054/60] 2026-02-09 → 2026-02-23

(209 records)

    [055/60] 2026-02-23 → 2026-03-09

(225 records)

    [056/60] 2026-03-09 → 2026-03-23

(195 records)

    [057/60] 2026-03-23 → 2026-04-06

(160 records)

    [058/60] 2026-04-06 → 2026-04-20

(186 records)

    [059/60] 2026-04-20 → 2026-05-04

(86 records)

    [060/60] 2026-05-04 → 2026-05-15

(157 records)

  so2 | sensor=7771973 | 60 windows
    [001/60] 2024-01-29 → 2024-02-12

(295 records)

    [002/60] 2024-02-12 → 2024-02-26

(335 records)

    [003/60] 2024-02-26 → 2024-03-11

(310 records)

    [004/60] 2024-03-11 → 2024-03-25

(217 records)

    [005/60] 2024-03-25 → 2024-04-08

(333 records)

    [006/60] 2024-04-08 → 2024-04-22

(279 records)

    [007/60] 2024-04-22 → 2024-05-06

(246 records)

    [008/60] 2024-05-06 → 2024-05-20

(328 records)

    [009/60] 2024-05-20 → 2024-06-03

(179 records)

    [010/60] 2024-06-03 → 2024-06-17

(290 records)

    [011/60] 2024-06-17 → 2024-07-01

(336 records)

    [012/60] 2024-07-01 → 2024-07-15

(335 records)

    [013/60] 2024-07-15 → 2024-07-29

(336 records)

    [014/60] 2024-07-29 → 2024-08-12

(331 records)

    [015/60] 2024-08-12 → 2024-08-26

(110 records)

    [016/60] 2024-08-26 → 2024-09-09

(0 records)

    [017/60] 2024-09-09 → 2024-09-23

(0 records)

    [018/60] 2024-09-23 → 2024-10-07

(0 records)

    [019/60] 2024-10-07 → 2024-10-21

(0 records)

    [020/60] 2024-10-21 → 2024-11-04

(0 records)

    [021/60] 2024-11-04 → 2024-11-18

(0 records)

    [022/60] 2024-11-18 → 2024-12-02

(0 records)

    [023/60] 2024-12-02 → 2024-12-16

(0 records)

    [024/60] 2024-12-16 → 2024-12-30

(0 records)

    [025/60] 2024-12-30 → 2025-01-13

(0 records)

    [026/60] 2025-01-13 → 2025-01-27

(0 records)

    [027/60] 2025-01-27 → 2025-02-10

(0 records)

    [028/60] 2025-02-10 → 2025-02-24

(0 records)

    [029/60] 2025-02-24 → 2025-03-10

(0 records)

    [030/60] 2025-03-10 → 2025-03-24

(0 records)

    [031/60] 2025-03-24 → 2025-04-07

(0 records)

    [032/60] 2025-04-07 → 2025-04-21

(0 records)

    [033/60] 2025-04-21 → 2025-05-05

(0 records)

    [034/60] 2025-05-05 → 2025-05-19

(0 records)

    [035/60] 2025-05-19 → 2025-06-02

(0 records)

    [036/60] 2025-06-02 → 2025-06-16

(0 records)

    [037/60] 2025-06-16 → 2025-06-30

(0 records)

    [038/60] 2025-06-30 → 2025-07-14

(0 records)

    [039/60] 2025-07-14 → 2025-07-28

(0 records)

    [040/60] 2025-07-28 → 2025-08-11

(0 records)

    [041/60] 2025-08-11 → 2025-08-25

(0 records)

    [042/60] 2025-08-25 → 2025-09-08

(0 records)

    [043/60] 2025-09-08 → 2025-09-22

(0 records)

    [044/60] 2025-09-22 → 2025-10-06

(0 records)

    [045/60] 2025-10-06 → 2025-10-20

(0 records)

    [046/60] 2025-10-20 → 2025-11-03

(0 records)

    [047/60] 2025-11-03 → 2025-11-17

(0 records)

    [048/60] 2025-11-17 → 2025-12-01

(0 records)

    [049/60] 2025-12-01 → 2025-12-15

(0 records)

    [050/60] 2025-12-15 → 2025-12-29

(0 records)

    [051/60] 2025-12-29 → 2026-01-12

(41 records)

    [052/60] 2026-01-12 → 2026-01-26

(195 records)

    [053/60] 2026-01-26 → 2026-02-09

(173 records)

    [054/60] 2026-02-09 → 2026-02-23

(209 records)

    [055/60] 2026-02-23 → 2026-03-09

(225 records)

    [056/60] 2026-03-09 → 2026-03-23

(195 records)

    [057/60] 2026-03-23 → 2026-04-06

(160 records)

    [058/60] 2026-04-06 → 2026-04-20

(186 records)

    [059/60] 2026-04-20 → 2026-05-04

(86 records)

    [060/60] 2026-05-04 → 2026-05-15

(161 records)

  Saved: 2161292_Số 46 phố Lưu Quang Vũ.csv  shape=(16654, 10)
  PM2.5 rows: 16003

============================================================
Station 2161293: Chúc Sơn
  Range: 2021-01-01  →  2026-05-15

  Sensors: 3
  co | sensor=7772064 | 29 windows
    [001/29] 2024-01-09 → 2024-01-23

(1 records)

    [002/29] 2024-01-23 → 2024-02-06

(0 records)

    [003/29] 2024-02-06 → 2024-02-20

(0 records)

    [004/29] 2024-02-20 → 2024-03-05

(0 records)

    [005/29] 2024-03-05 → 2024-03-19

(0 records)

    [006/29] 2024-03-19 → 2024-04-02

(0 records)

    [007/29] 2024-04-02 → 2024-04-16

(0 records)

    [008/29] 2024-04-16 → 2024-04-30

(0 records)

    [009/29] 2024-04-30 → 2024-05-14

(0 records)

    [010/29] 2024-05-14 → 2024-05-28

(0 records)

    [011/29] 2024-05-28 → 2024-06-11

(0 records)

    [012/29] 2024-06-11 → 2024-06-25

(0 records)

    [013/29] 2024-06-25 → 2024-07-09

(0 records)

    [014/29] 2024-07-09 → 2024-07-23

(0 records)

    [015/29] 2024-07-23 → 2024-08-06

(0 records)

    [016/29] 2024-08-06 → 2024-08-20

(0 records)

    [017/29] 2024-08-20 → 2024-09-03

(0 records)

    [018/29] 2024-09-03 → 2024-09-17

(0 records)

    [019/29] 2024-09-17 → 2024-10-01

(0 records)

    [020/29] 2024-10-01 → 2024-10-15

(301 records)

    [021/29] 2024-10-15 → 2024-10-29

(336 records)

    [022/29] 2024-10-29 → 2024-11-12

(295 records)

    [023/29] 2024-11-12 → 2024-11-26

(336 records)

    [024/29] 2024-11-26 → 2024-12-10

(334 records)

    [025/29] 2024-12-10 → 2024-12-24

(333 records)

    [026/29] 2024-12-24 → 2025-01-07

(329 records)

    [027/29] 2025-01-07 → 2025-01-21

(336 records)

    [028/29] 2025-01-21 → 2025-02-04

(318 records)

    [029/29] 2025-02-04 → 2025-02-05

(11 records)

  no2 | sensor=7772027 | 29 windows
    [001/29] 2024-01-09 → 2024-01-23

(1 records)

    [002/29] 2024-01-23 → 2024-02-06

(0 records)

    [003/29] 2024-02-06 → 2024-02-20

(0 records)

    [004/29] 2024-02-20 → 2024-03-05

(0 records)

    [005/29] 2024-03-05 → 2024-03-19

(0 records)

    [006/29] 2024-03-19 → 2024-04-02

(0 records)

    [007/29] 2024-04-02 → 2024-04-16

(0 records)

    [008/29] 2024-04-16 → 2024-04-30

(0 records)

    [009/29] 2024-04-30 → 2024-05-14

(0 records)

    [010/29] 2024-05-14 → 2024-05-28

(0 records)

    [011/29] 2024-05-28 → 2024-06-11

(0 records)

    [012/29] 2024-06-11 → 2024-06-25

(0 records)

    [013/29] 2024-06-25 → 2024-07-09

(0 records)

    [014/29] 2024-07-09 → 2024-07-23

(0 records)

    [015/29] 2024-07-23 → 2024-08-06

(0 records)

    [016/29] 2024-08-06 → 2024-08-20

(0 records)

    [017/29] 2024-08-20 → 2024-09-03

(0 records)

    [018/29] 2024-09-03 → 2024-09-17

(0 records)

    [019/29] 2024-09-17 → 2024-10-01

(0 records)

    [020/29] 2024-10-01 → 2024-10-15

(301 records)

    [021/29] 2024-10-15 → 2024-10-29

(336 records)

    [022/29] 2024-10-29 → 2024-11-12

(295 records)

    [023/29] 2024-11-12 → 2024-11-26

(336 records)

    [024/29] 2024-11-26 → 2024-12-10

(334 records)

    [025/29] 2024-12-10 → 2024-12-24

(336 records)

    [026/29] 2024-12-24 → 2025-01-07

(329 records)

    [027/29] 2025-01-07 → 2025-01-21

(336 records)

    [028/29] 2025-01-21 → 2025-02-04

(318 records)

    [029/29] 2025-02-04 → 2025-02-05

(11 records)

  pm25 | sensor=7772046 | 29 windows
    [001/29] 2024-01-09 → 2024-01-23

(1 records)

    [002/29] 2024-01-23 → 2024-02-06

(0 records)

    [003/29] 2024-02-06 → 2024-02-20

(0 records)

    [004/29] 2024-02-20 → 2024-03-05

(0 records)

    [005/29] 2024-03-05 → 2024-03-19

(0 records)

    [006/29] 2024-03-19 → 2024-04-02

(0 records)

    [007/29] 2024-04-02 → 2024-04-16

(0 records)

    [008/29] 2024-04-16 → 2024-04-30

(0 records)

    [009/29] 2024-04-30 → 2024-05-14

(0 records)

    [010/29] 2024-05-14 → 2024-05-28

(0 records)

    [011/29] 2024-05-28 → 2024-06-11

(0 records)

    [012/29] 2024-06-11 → 2024-06-25

(0 records)

    [013/29] 2024-06-25 → 2024-07-09

(0 records)

    [014/29] 2024-07-09 → 2024-07-23

(0 records)

    [015/29] 2024-07-23 → 2024-08-06

(0 records)

    [016/29] 2024-08-06 → 2024-08-20

(0 records)

    [017/29] 2024-08-20 → 2024-09-03

(0 records)

    [018/29] 2024-09-03 → 2024-09-17

(0 records)

    [019/29] 2024-09-17 → 2024-10-01

(0 records)

    [020/29] 2024-10-01 → 2024-10-15

(301 records)

    [021/29] 2024-10-15 → 2024-10-29

(336 records)

    [022/29] 2024-10-29 → 2024-11-12

(295 records)

    [023/29] 2024-11-12 → 2024-11-26

(336 records)

    [024/29] 2024-11-26 → 2024-12-10

(334 records)

    [025/29] 2024-12-10 → 2024-12-24

(325 records)

    [026/29] 2024-12-24 → 2025-01-07

(329 records)

    [027/29] 2025-01-07 → 2025-01-21

(336 records)

    [028/29] 2025-01-21 → 2025-02-04

(318 records)

    [029/29] 2025-02-04 → 2025-02-05

(11 records)

  Saved: 2161293_Chúc Sơn.csv  shape=(2933, 10)
  PM2.5 rows: 2922

============================================================
Station 2161294: Cung thiếu nhi
  Range: 2021-01-01  →  2026-05-15

  Sensors: 3
  co | sensor=7772083 | 27 windows
    [001/27] 2024-01-29 → 2024-02-12

(95 records)

    [002/27] 2024-02-12 → 2024-02-26

(129 records)

    [003/27] 2024-02-26 → 2024-03-11

(149 records)

    [004/27] 2024-03-11 → 2024-03-25

(0 records)

    [005/27] 2024-03-25 → 2024-04-08

(0 records)

    [006/27] 2024-04-08 → 2024-04-22

(0 records)

    [007/27] 2024-04-22 → 2024-05-06

(0 records)

    [008/27] 2024-05-06 → 2024-05-20

(0 records)

    [009/27] 2024-05-20 → 2024-06-03

(0 records)

    [010/27] 2024-06-03 → 2024-06-17

(0 records)

    [011/27] 2024-06-17 → 2024-07-01

(0 records)

    [012/27] 2024-07-01 → 2024-07-15

(0 records)

    [013/27] 2024-07-15 → 2024-07-29

(0 records)

    [014/27] 2024-07-29 → 2024-08-12

(0 records)

    [015/27] 2024-08-12 → 2024-08-26

(0 records)

    [016/27] 2024-08-26 → 2024-09-09

(0 records)

    [017/27] 2024-09-09 → 2024-09-23

(29 records)

    [018/27] 2024-09-23 → 2024-10-07

(223 records)

    [019/27] 2024-10-07 → 2024-10-21

(329 records)

    [020/27] 2024-10-21 → 2024-11-04

(331 records)

    [021/27] 2024-11-04 → 2024-11-18

(300 records)

    [022/27] 2024-11-18 → 2024-12-02

(336 records)

    [023/27] 2024-12-02 → 2024-12-16

(315 records)

    [024/27] 2024-12-16 → 2024-12-30

(336 records)

    [025/27] 2024-12-30 → 2025-01-13

(328 records)

    [026/27] 2025-01-13 → 2025-01-27

(319 records)

    [027/27] 2025-01-27 → 2025-02-05

(208 records)

  no2 | sensor=7771978 | 27 windows
    [001/27] 2024-01-29 → 2024-02-12

(95 records)

    [002/27] 2024-02-12 → 2024-02-26

(129 records)

    [003/27] 2024-02-26 → 2024-03-11

(149 records)

    [004/27] 2024-03-11 → 2024-03-25

(0 records)

    [005/27] 2024-03-25 → 2024-04-08

(0 records)

    [006/27] 2024-04-08 → 2024-04-22

(0 records)

    [007/27] 2024-04-22 → 2024-05-06

(0 records)

    [008/27] 2024-05-06 → 2024-05-20

(0 records)

    [009/27] 2024-05-20 → 2024-06-03

(0 records)

    [010/27] 2024-06-03 → 2024-06-17

(0 records)

    [011/27] 2024-06-17 → 2024-07-01

(0 records)

    [012/27] 2024-07-01 → 2024-07-15

(0 records)

    [013/27] 2024-07-15 → 2024-07-29

(0 records)

    [014/27] 2024-07-29 → 2024-08-12

(0 records)

    [015/27] 2024-08-12 → 2024-08-26

(0 records)

    [016/27] 2024-08-26 → 2024-09-09

(0 records)

    [017/27] 2024-09-09 → 2024-09-23

(29 records)

    [018/27] 2024-09-23 → 2024-10-07

(223 records)

    [019/27] 2024-10-07 → 2024-10-21

(329 records)

    [020/27] 2024-10-21 → 2024-11-04

(331 records)

    [021/27] 2024-11-04 → 2024-11-18

(300 records)

    [022/27] 2024-11-18 → 2024-12-02

(336 records)

    [023/27] 2024-12-02 → 2024-12-16

(317 records)

    [024/27] 2024-12-16 → 2024-12-30

(336 records)

    [025/27] 2024-12-30 → 2025-01-13

(328 records)

    [026/27] 2025-01-13 → 2025-01-27

(319 records)

    [027/27] 2025-01-27 → 2025-02-05

(208 records)

  pm25 | sensor=7772104 | 27 windows
    [001/27] 2024-01-29 → 2024-02-12

(95 records)

    [002/27] 2024-02-12 → 2024-02-26

(129 records)

    [003/27] 2024-02-26 → 2024-03-11

(149 records)

    [004/27] 2024-03-11 → 2024-03-25

(0 records)

    [005/27] 2024-03-25 → 2024-04-08

(0 records)

    [006/27] 2024-04-08 → 2024-04-22

(0 records)

    [007/27] 2024-04-22 → 2024-05-06

(0 records)

    [008/27] 2024-05-06 → 2024-05-20

(0 records)

    [009/27] 2024-05-20 → 2024-06-03

(0 records)

    [010/27] 2024-06-03 → 2024-06-17

(0 records)

    [011/27] 2024-06-17 → 2024-07-01

(0 records)

    [012/27] 2024-07-01 → 2024-07-15

(0 records)

    [013/27] 2024-07-15 → 2024-07-29

(0 records)

    [014/27] 2024-07-29 → 2024-08-12

(0 records)

    [015/27] 2024-08-12 → 2024-08-26

(0 records)

    [016/27] 2024-08-26 → 2024-09-09

(0 records)

    [017/27] 2024-09-09 → 2024-09-23

(29 records)

    [018/27] 2024-09-23 → 2024-10-07

(223 records)

    [019/27] 2024-10-07 → 2024-10-21

(329 records)

    [020/27] 2024-10-21 → 2024-11-04

(331 records)

    [021/27] 2024-11-04 → 2024-11-18

(300 records)

    [022/27] 2024-11-18 → 2024-12-02

(336 records)

    [023/27] 2024-12-02 → 2024-12-16

(306 records)

    [024/27] 2024-12-16 → 2024-12-30

(336 records)

    [025/27] 2024-12-30 → 2025-01-13

(328 records)

    [026/27] 2025-01-13 → 2025-01-27

(319 records)

    [027/27] 2025-01-27 → 2025-02-05

(208 records)

  Saved: 2161294_Cung thiếu nhi.csv  shape=(3429, 10)
  PM2.5 rows: 3418

============================================================
Station 2161295: Đầm Trấu
  Range: 2021-01-01  →  2026-05-15

  Sensors: 3
  co | sensor=7772081 | 1 windows
    [001/1] 2024-01-29 → 2024-01-30

(8 records)

  no2 | sensor=7772045 | 1 windows
    [001/1] 2024-01-29 → 2024-01-30

(11 records)

  pm25 | sensor=7771992 | 1 windows
    [001/1] 2024-01-29 → 2024-01-30

(11 records)

  Saved: 2161295_Đầm Trấu.csv  shape=(11, 10)
  PM2.5 rows: 11

============================================================
Station 2161296: Đào Duy Từ
  Range: 2021-01-01  →  2026-05-15

  Sensors: 3
  co | sensor=7771983 | 37 windows
    [001/37] 2024-01-15 → 2024-01-29

(2 records)

    [002/37] 2024-01-29 → 2024-02-12

(0 records)

    [003/37] 2024-02-12 → 2024-02-26

(0 records)

    [004/37] 2024-02-26 → 2024-03-11

(0 records)

    [005/37] 2024-03-11 → 2024-03-25

(0 records)

    [006/37] 2024-03-25 → 2024-04-08

(0 records)

    [007/37] 2024-04-08 → 2024-04-22

(0 records)

    [008/37] 2024-04-22 → 2024-05-06

(0 records)

    [009/37] 2024-05-06 → 2024-05-20

(0 records)

    [010/37] 2024-05-20 → 2024-06-03

(0 records)

    [011/37] 2024-06-03 → 2024-06-17

(0 records)

    [012/37] 2024-06-17 → 2024-07-01

(0 records)

    [013/37] 2024-07-01 → 2024-07-15

(0 records)

    [014/37] 2024-07-15 → 2024-07-29

(0 records)

    [015/37] 2024-07-29 → 2024-08-12

(0 records)

    [016/37] 2024-08-12 → 2024-08-26

(0 records)

    [017/37] 2024-08-26 → 2024-09-09

(0 records)

    [018/37] 2024-09-09 → 2024-09-23

(41 records)

    [019/37] 2024-09-23 → 2024-10-07

(330 records)

    [020/37] 2024-10-07 → 2024-10-21

(329 records)

    [021/37] 2024-10-21 → 2024-11-04

(331 records)

    [022/37] 2024-11-04 → 2024-11-18

(300 records)

    [023/37] 2024-11-18 → 2024-12-02

(336 records)

    [024/37] 2024-12-02 → 2024-12-16

(334 records)

    [025/37] 2024-12-16 → 2024-12-30

(336 records)

    [026/37] 2024-12-30 → 2025-01-13

(328 records)

    [027/37] 2025-01-13 → 2025-01-27

(319 records)

    [028/37] 2025-01-27 → 2025-02-10

(336 records)

    [029/37] 2025-02-10 → 2025-02-24

(335 records)

    [030/37] 2025-02-24 → 2025-03-10

(336 records)

    [031/37] 2025-03-10 → 2025-03-24

(336 records)

    [032/37] 2025-03-24 → 2025-04-07

(336 records)

    [033/37] 2025-04-07 → 2025-04-21

(336 records)

    [034/37] 2025-04-21 → 2025-05-05

(234 records)

    [035/37] 2025-05-05 → 2025-05-19

(335 records)

    [036/37] 2025-05-19 → 2025-06-02

(327 records)

    [037/37] 2025-06-02 → 2025-06-10

(187 records)

  no2 | sensor=7772030 | 37 windows
    [001/37] 2024-01-15 → 2024-01-29

(2 records)

    [002/37] 2024-01-29 → 2024-02-12

(0 records)

    [003/37] 2024-02-12 → 2024-02-26

(0 records)

    [004/37] 2024-02-26 → 2024-03-11

(0 records)

    [005/37] 2024-03-11 → 2024-03-25

(0 records)

    [006/37] 2024-03-25 → 2024-04-08

(0 records)

    [007/37] 2024-04-08 → 2024-04-22

(0 records)

    [008/37] 2024-04-22 → 2024-05-06

(0 records)

    [009/37] 2024-05-06 → 2024-05-20

(0 records)

    [010/37] 2024-05-20 → 2024-06-03

(0 records)

    [011/37] 2024-06-03 → 2024-06-17

(0 records)

    [012/37] 2024-06-17 → 2024-07-01

(0 records)

    [013/37] 2024-07-01 → 2024-07-15

(0 records)

    [014/37] 2024-07-15 → 2024-07-29

(0 records)

    [015/37] 2024-07-29 → 2024-08-12

(0 records)

    [016/37] 2024-08-12 → 2024-08-26

(0 records)

    [017/37] 2024-08-26 → 2024-09-09

(0 records)

    [018/37] 2024-09-09 → 2024-09-23

(41 records)

    [019/37] 2024-09-23 → 2024-10-07

(330 records)

    [020/37] 2024-10-07 → 2024-10-21

(329 records)

    [021/37] 2024-10-21 → 2024-11-04

(331 records)

    [022/37] 2024-11-04 → 2024-11-18

(300 records)

    [023/37] 2024-11-18 → 2024-12-02

(336 records)

    [024/37] 2024-12-02 → 2024-12-16

(336 records)

    [025/37] 2024-12-16 → 2024-12-30

(336 records)

    [026/37] 2024-12-30 → 2025-01-13

(328 records)

    [027/37] 2025-01-13 → 2025-01-27

(319 records)

    [028/37] 2025-01-27 → 2025-02-10

(336 records)

    [029/37] 2025-02-10 → 2025-02-24

(335 records)

    [030/37] 2025-02-24 → 2025-03-10

(336 records)

    [031/37] 2025-03-10 → 2025-03-24

(336 records)

    [032/37] 2025-03-24 → 2025-04-07

(336 records)

    [033/37] 2025-04-07 → 2025-04-21

(336 records)

    [034/37] 2025-04-21 → 2025-05-05

(234 records)

    [035/37] 2025-05-05 → 2025-05-19

(335 records)

    [036/37] 2025-05-19 → 2025-06-02

(327 records)

    [037/37] 2025-06-02 → 2025-06-10

(187 records)

  pm25 | sensor=7772040 | 37 windows
    [001/37] 2024-01-15 → 2024-01-29

(2 records)

    [002/37] 2024-01-29 → 2024-02-12

(0 records)

    [003/37] 2024-02-12 → 2024-02-26

(0 records)

    [004/37] 2024-02-26 → 2024-03-11

(0 records)

    [005/37] 2024-03-11 → 2024-03-25

(0 records)

    [006/37] 2024-03-25 → 2024-04-08

(0 records)

    [007/37] 2024-04-08 → 2024-04-22

(0 records)

    [008/37] 2024-04-22 → 2024-05-06

(0 records)

    [009/37] 2024-05-06 → 2024-05-20

(0 records)

    [010/37] 2024-05-20 → 2024-06-03

(0 records)

    [011/37] 2024-06-03 → 2024-06-17

(0 records)

    [012/37] 2024-06-17 → 2024-07-01

(0 records)

    [013/37] 2024-07-01 → 2024-07-15

(0 records)

    [014/37] 2024-07-15 → 2024-07-29

(0 records)

    [015/37] 2024-07-29 → 2024-08-12

(0 records)

    [016/37] 2024-08-12 → 2024-08-26

(0 records)

    [017/37] 2024-08-26 → 2024-09-09

(0 records)

    [018/37] 2024-09-09 → 2024-09-23

(41 records)

    [019/37] 2024-09-23 → 2024-10-07

(330 records)

    [020/37] 2024-10-07 → 2024-10-21

(329 records)

    [021/37] 2024-10-21 → 2024-11-04

(331 records)

    [022/37] 2024-11-04 → 2024-11-18

(300 records)

    [023/37] 2024-11-18 → 2024-12-02

(336 records)

    [024/37] 2024-12-02 → 2024-12-16

(325 records)

    [025/37] 2024-12-16 → 2024-12-30

(336 records)

    [026/37] 2024-12-30 → 2025-01-13

(328 records)

    [027/37] 2025-01-13 → 2025-01-27

(319 records)

    [028/37] 2025-01-27 → 2025-02-10

(336 records)

    [029/37] 2025-02-10 → 2025-02-24

(335 records)

    [030/37] 2025-02-24 → 2025-03-10

(336 records)

    [031/37] 2025-03-10 → 2025-03-24

(336 records)

    [032/37] 2025-03-24 → 2025-04-07

(336 records)

    [033/37] 2025-04-07 → 2025-04-21

(336 records)

    [034/37] 2025-04-21 → 2025-05-05

(234 records)

    [035/37] 2025-05-05 → 2025-05-19

(335 records)

    [036/37] 2025-05-19 → 2025-06-02

(327 records)

    [037/37] 2025-06-02 → 2025-06-10

(187 records)

  Saved: 2161296_Đào Duy Từ.csv  shape=(6086, 10)
  PM2.5 rows: 6075

============================================================
Station 2161298: Đông Kinh Nghĩa Thục
  Range: 2021-01-01  →  2026-05-15

  Sensors: 3
  co | sensor=7772090 | 6 windows
    [001/6] 2024-01-29 → 2024-02-12

(94 records)

    [002/6] 2024-02-12 → 2024-02-26

(129 records)

    [003/6] 2024-02-26 → 2024-03-11

(234 records)

    [004/6] 2024-03-11 → 2024-03-25

(134 records)

    [005/6] 2024-03-25 → 2024-04-08

(199 records)

    [006/6] 2024-04-08 → 2024-04-15

(62 records)

  no2 | sensor=7772026 | 6 windows
    [001/6] 2024-01-29 → 2024-02-12

(94 records)

    [002/6] 2024-02-12 → 2024-02-26

(129 records)

    [003/6] 2024-02-26 → 2024-03-11

(234 records)

    [004/6] 2024-03-11 → 2024-03-25

(134 records)

    [005/6] 2024-03-25 → 2024-04-08

(199 records)

    [006/6] 2024-04-08 → 2024-04-15

(62 records)

  pm25 | sensor=7772025 | 6 windows
    [001/6] 2024-01-29 → 2024-02-12

(94 records)

    [002/6] 2024-02-12 → 2024-02-26

(129 records)

    [003/6] 2024-02-26 → 2024-03-11

(234 records)

    [004/6] 2024-03-11 → 2024-03-25

(134 records)

    [005/6] 2024-03-25 → 2024-04-08

(199 records)

    [006/6] 2024-04-08 → 2024-04-15

(62 records)

  Saved: 2161298_Đông Kinh Nghĩa Thục.csv  shape=(852, 10)
  PM2.5 rows: 852

============================================================
Station 2161299: Hàng Đậu
  Range: 2021-01-01  →  2026-05-15

  Sensors: 3
  co | sensor=7772019 | 22 windows
    [001/22] 2024-01-29 → 2024-02-12

(91 records)

    [002/22] 2024-02-12 → 2024-02-26

(130 records)

    [003/22] 2024-02-26 → 2024-03-11

(233 records)

    [004/22] 2024-03-11 → 2024-03-25

(134 records)

    [005/22] 2024-03-25 → 2024-04-08

(198 records)

    [006/22] 2024-04-08 → 2024-04-22

(165 records)

    [007/22] 2024-04-22 → 2024-05-06

(204 records)

    [008/22] 2024-05-06 → 2024-05-20

(243 records)

    [009/22] 2024-05-20 → 2024-06-03

(117 records)

    [010/22] 2024-06-03 → 2024-06-17

(203 records)

    [011/22] 2024-06-17 → 2024-07-01

(167 records)

    [012/22] 2024-07-01 → 2024-07-15

(0 records)

    [013/22] 2024-07-15 → 2024-07-29

(0 records)

    [014/22] 2024-07-29 → 2024-08-12

(0 records)

    [015/22] 2024-08-12 → 2024-08-26

(0 records)

    [016/22] 2024-08-26 → 2024-09-09

(0 records)

    [017/22] 2024-09-09 → 2024-09-23

(0 records)

    [018/22] 2024-09-23 → 2024-10-07

(220 records)

    [019/22] 2024-10-07 → 2024-10-21

(329 records)

    [020/22] 2024-10-21 → 2024-11-04

(331 records)

    [021/22] 2024-11-04 → 2024-11-18

(300 records)

    [022/22] 2024-11-18 → 2024-11-26

(203 records)

  no2 | sensor=7772102 | 22 windows
    [001/22] 2024-01-29 → 2024-02-12

(92 records)

    [002/22] 2024-02-12 → 2024-02-26

(130 records)

    [003/22] 2024-02-26 → 2024-03-11

(233 records)

    [004/22] 2024-03-11 → 2024-03-25

(134 records)

    [005/22] 2024-03-25 → 2024-04-08

(202 records)

    [006/22] 2024-04-08 → 2024-04-22

(166 records)

    [007/22] 2024-04-22 → 2024-05-06

(204 records)

    [008/22] 2024-05-06 → 2024-05-20

(243 records)

    [009/22] 2024-05-20 → 2024-06-03

(117 records)

    [010/22] 2024-06-03 → 2024-06-17

(203 records)

    [011/22] 2024-06-17 → 2024-07-01

(167 records)

    [012/22] 2024-07-01 → 2024-07-15

(0 records)

    [013/22] 2024-07-15 → 2024-07-29

(0 records)

    [014/22] 2024-07-29 → 2024-08-12

(0 records)

    [015/22] 2024-08-12 → 2024-08-26

(0 records)

    [016/22] 2024-08-26 → 2024-09-09

(0 records)

    [017/22] 2024-09-09 → 2024-09-23

(0 records)

    [018/22] 2024-09-23 → 2024-10-07

(221 records)

    [019/22] 2024-10-07 → 2024-10-21

(329 records)

    [020/22] 2024-10-21 → 2024-11-04

(331 records)

    [021/22] 2024-11-04 → 2024-11-18

(300 records)

    [022/22] 2024-11-18 → 2024-11-26

(203 records)

  pm25 | sensor=7771996 | 22 windows
    [001/22] 2024-01-29 → 2024-02-12

(92 records)

    [002/22] 2024-02-12 → 2024-02-26

(130 records)

    [003/22] 2024-02-26 → 2024-03-11

(233 records)

    [004/22] 2024-03-11 → 2024-03-25

(134 records)

    [005/22] 2024-03-25 → 2024-04-08

(198 records)

    [006/22] 2024-04-08 → 2024-04-22

(163 records)

    [007/22] 2024-04-22 → 2024-05-06

(204 records)

    [008/22] 2024-05-06 → 2024-05-20

(243 records)

    [009/22] 2024-05-20 → 2024-06-03

(117 records)

    [010/22] 2024-06-03 → 2024-06-17

(203 records)

    [011/22] 2024-06-17 → 2024-07-01

(167 records)

    [012/22] 2024-07-01 → 2024-07-15

(0 records)

    [013/22] 2024-07-15 → 2024-07-29

(0 records)

    [014/22] 2024-07-29 → 2024-08-12

(0 records)

    [015/22] 2024-08-12 → 2024-08-26

(0 records)

    [016/22] 2024-08-26 → 2024-09-09

(0 records)

    [017/22] 2024-09-09 → 2024-09-23

(0 records)

    [018/22] 2024-09-23 → 2024-10-07

(220 records)

    [019/22] 2024-10-07 → 2024-10-21

(329 records)

    [020/22] 2024-10-21 → 2024-11-04

(331 records)

    [021/22] 2024-11-04 → 2024-11-18

(300 records)

    [022/22] 2024-11-18 → 2024-11-26

(203 records)

  Saved: 2161299_Hàng Đậu.csv  shape=(3275, 10)
  PM2.5 rows: 3267

============================================================
Station 2161300: Hoàn Kiếm
  Range: 2021-01-01  →  2026-05-15

  Sensors: 3
  co | sensor=7772043 | 1 windows
    [001/1] 2024-01-29 → 2024-01-31

(22 records)

  no2 | sensor=7771987 | 1 windows
    [001/1] 2024-01-29 → 2024-01-31

(22 records)

  pm25 | sensor=7771988 | 1 windows
    [001/1] 2024-01-29 → 2024-01-31

(22 records)

  Saved: 2161300_Hoàn Kiếm.csv  shape=(22, 10)
  PM2.5 rows: 22

============================================================
Station 2161301: Khương Trung
  Range: 2021-01-01  →  2026-05-15

  Sensors: 3
  co | sensor=7772052 | 23 windows
    [001/23] 2024-01-29 → 2024-02-12

(94 records)

    [002/23] 2024-02-12 → 2024-02-26

(129 records)

    [003/23] 2024-02-26 → 2024-03-11

(235 records)

    [004/23] 2024-03-11 → 2024-03-25

(134 records)

    [005/23] 2024-03-25 → 2024-04-08

(172 records)

    [006/23] 2024-04-08 → 2024-04-22

(0 records)

    [007/23] 2024-04-22 → 2024-05-06

(0 records)

    [008/23] 2024-05-06 → 2024-05-20

(0 records)

    [009/23] 2024-05-20 → 2024-06-03

(0 records)

    [010/23] 2024-06-03 → 2024-06-17

(0 records)

    [011/23] 2024-06-17 → 2024-07-01

(0 records)

    [012/23] 2024-07-01 → 2024-07-15

(0 records)

    [013/23] 2024-07-15 → 2024-07-29

(0 records)

    [014/23] 2024-07-29 → 2024-08-12

(0 records)

    [015/23] 2024-08-12 → 2024-08-26

(0 records)

    [016/23] 2024-08-26 → 2024-09-09

(0 records)

    [017/23] 2024-09-09 → 2024-09-23

(0 records)

    [018/23] 2024-09-23 → 2024-10-07

(256 records)

    [019/23] 2024-10-07 → 2024-10-21

(328 records)

    [020/23] 2024-10-21 → 2024-11-04

(328 records)

    [021/23] 2024-11-04 → 2024-11-18

(300 records)

    [022/23] 2024-11-18 → 2024-12-02

(336 records)

    [023/23] 2024-12-02 → 2024-12-11

(224 records)

  no2 | sensor=7772050 | 23 windows
    [001/23] 2024-01-29 → 2024-02-12

(94 records)

    [002/23] 2024-02-12 → 2024-02-26

(128 records)

    [003/23] 2024-02-26 → 2024-03-11

(235 records)

    [004/23] 2024-03-11 → 2024-03-25

(131 records)

    [005/23] 2024-03-25 → 2024-04-08

(171 records)

    [006/23] 2024-04-08 → 2024-04-22

(0 records)

    [007/23] 2024-04-22 → 2024-05-06

(0 records)

    [008/23] 2024-05-06 → 2024-05-20

(0 records)

    [009/23] 2024-05-20 → 2024-06-03

(0 records)

    [010/23] 2024-06-03 → 2024-06-17

(0 records)

    [011/23] 2024-06-17 → 2024-07-01

(0 records)

    [012/23] 2024-07-01 → 2024-07-15

(0 records)

    [013/23] 2024-07-15 → 2024-07-29

(0 records)

    [014/23] 2024-07-29 → 2024-08-12

(0 records)

    [015/23] 2024-08-12 → 2024-08-26

(0 records)

    [016/23] 2024-08-26 → 2024-09-09

(0 records)

    [017/23] 2024-09-09 → 2024-09-23

(0 records)

    [018/23] 2024-09-23 → 2024-10-07

(251 records)

    [019/23] 2024-10-07 → 2024-10-21

(322 records)

    [020/23] 2024-10-21 → 2024-11-04

(322 records)

    [021/23] 2024-11-04 → 2024-11-18

(295 records)

    [022/23] 2024-11-18 → 2024-12-02

(332 records)

    [023/23] 2024-12-02 → 2024-12-11

(224 records)

  pm25 | sensor=7772073 | 23 windows
    [001/23] 2024-01-29 → 2024-02-12

(90 records)

    [002/23] 2024-02-12 → 2024-02-26

(126 records)

    [003/23] 2024-02-26 → 2024-03-11

(220 records)

    [004/23] 2024-03-11 → 2024-03-25

(125 records)

    [005/23] 2024-03-25 → 2024-04-08

(172 records)

    [006/23] 2024-04-08 → 2024-04-22

(0 records)

    [007/23] 2024-04-22 → 2024-05-06

(0 records)

    [008/23] 2024-05-06 → 2024-05-20

(0 records)

    [009/23] 2024-05-20 → 2024-06-03

(0 records)

    [010/23] 2024-06-03 → 2024-06-17

(0 records)

    [011/23] 2024-06-17 → 2024-07-01

(0 records)

    [012/23] 2024-07-01 → 2024-07-15

(0 records)

    [013/23] 2024-07-15 → 2024-07-29

(0 records)

    [014/23] 2024-07-29 → 2024-08-12

(0 records)

    [015/23] 2024-08-12 → 2024-08-26

(0 records)

    [016/23] 2024-08-26 → 2024-09-09

(0 records)

    [017/23] 2024-09-09 → 2024-09-23

(0 records)

    [018/23] 2024-09-23 → 2024-10-07

(256 records)

    [019/23] 2024-10-07 → 2024-10-21

(328 records)

    [020/23] 2024-10-21 → 2024-11-04

(328 records)

    [021/23] 2024-11-04 → 2024-11-18

(300 records)

    [022/23] 2024-11-18 → 2024-12-02

(336 records)

    [023/23] 2024-12-02 → 2024-12-11

(225 records)

  Saved: 2161301_Khương Trung.csv  shape=(2538, 10)
  PM2.5 rows: 2506

============================================================
Station 2161303: Kim Liên
  Range: 2021-01-01  →  2026-05-15

  Sensors: 3
  co | sensor=7772080 | 4 windows
    [001/4] 2024-01-29 → 2024-02-12

(89 records)

    [002/4] 2024-02-12 → 2024-02-26

(126 records)

    [003/4] 2024-02-26 → 2024-03-11

(235 records)

    [004/4] 2024-03-11 → 2024-03-22

(113 records)

  no2 | sensor=7772093 | 4 windows
    [001/4] 2024-01-29 → 2024-02-12

(89 records)

    [002/4] 2024-02-12 → 2024-02-26

(127 records)

    [003/4] 2024-02-26 → 2024-03-11

(235 records)

    [004/4] 2024-03-11 → 2024-03-22

(113 records)

  pm25 | sensor=7772038 | 4 windows
    [001/4] 2024-01-29 → 2024-02-12

(82 records)

    [002/4] 2024-02-12 → 2024-02-26

(93 records)

    [003/4] 2024-02-26 → 2024-03-11

(196 records)

    [004/4] 2024-03-11 → 2024-03-22

(101 records)

  Saved: 2161303_Kim Liên.csv  shape=(566, 10)
  PM2.5 rows: 472

============================================================
Station 2161304: Lê Trực
  Range: 2021-01-01  →  2026-05-15

  Sensors: 3
  co | sensor=7772010 | 1 windows
    [001/1] 2024-01-29 → 2024-01-31

(14 records)

  no2 | sensor=7772021 | 1 windows
    [001/1] 2024-01-29 → 2024-01-31

(13 records)

  pm25 | sensor=7772096 | 1 windows
    [001/1] 2024-01-29 → 2024-01-31

(13 records)

  Saved: 2161304_Lê Trực.csv  shape=(14, 10)
  PM2.5 rows: 13

============================================================
Station 2161306: Minh Khai - Bắc Từ Liêm
  Range: 2021-01-01  →  2026-05-15

  Sensors: 5
  co | sensor=7771995 | 60 windows
    [001/60] 2024-01-29 → 2024-02-12

(280 records)

    [002/60] 2024-02-12 → 2024-02-26

(334 records)

    [003/60] 2024-02-26 → 2024-03-11

(293 records)

    [004/60] 2024-03-11 → 2024-03-25

(155 records)

    [005/60] 2024-03-25 → 2024-04-08

(112 records)

    [006/60] 2024-04-08 → 2024-04-22

(121 records)

    [007/60] 2024-04-22 → 2024-05-06

(52 records)

    [008/60] 2024-05-06 → 2024-05-20

(247 records)

    [009/60] 2024-05-20 → 2024-06-03

(63 records)

    [010/60] 2024-06-03 → 2024-06-17

(125 records)

    [011/60] 2024-06-17 → 2024-07-01

(69 records)

    [012/60] 2024-07-01 → 2024-07-15

(187 records)

    [013/60] 2024-07-15 → 2024-07-29

(261 records)

    [014/60] 2024-07-29 → 2024-08-12

(214 records)

    [015/60] 2024-08-12 → 2024-08-26

(32 records)

    [016/60] 2024-08-26 → 2024-09-09

(7 records)

    [017/60] 2024-09-09 → 2024-09-23

(73 records)

    [018/60] 2024-09-23 → 2024-10-07

(23 records)

    [019/60] 2024-10-07 → 2024-10-21

(15 records)

    [020/60] 2024-10-21 → 2024-11-04

(135 records)

    [021/60] 2024-11-04 → 2024-11-18

(102 records)

    [022/60] 2024-11-18 → 2024-12-02

(68 records)

    [023/60] 2024-12-02 → 2024-12-16

(0 records)

    [024/60] 2024-12-16 → 2024-12-30

(38 records)

    [025/60] 2024-12-30 → 2025-01-13

(104 records)

    [026/60] 2025-01-13 → 2025-01-27

(20 records)

    [027/60] 2025-01-27 → 2025-02-10

(156 records)

    [028/60] 2025-02-10 → 2025-02-24

(336 records)

    [029/60] 2025-02-24 → 2025-03-10

(334 records)

    [030/60] 2025-03-10 → 2025-03-24

(289 records)

    [031/60] 2025-03-24 → 2025-04-07

(252 records)

    [032/60] 2025-04-07 → 2025-04-21

(335 records)

    [033/60] 2025-04-21 → 2025-05-05

(158 records)

    [034/60] 2025-05-05 → 2025-05-19

(334 records)

    [035/60] 2025-05-19 → 2025-06-02

(329 records)

    [036/60] 2025-06-02 → 2025-06-16

(158 records)

    [037/60] 2025-06-16 → 2025-06-30

(75 records)

    [038/60] 2025-06-30 → 2025-07-14

(111 records)

    [039/60] 2025-07-14 → 2025-07-28

(0 records)

    [040/60] 2025-07-28 → 2025-08-11

(0 records)

    [041/60] 2025-08-11 → 2025-08-25

(0 records)

    [042/60] 2025-08-25 → 2025-09-08

(0 records)

    [043/60] 2025-09-08 → 2025-09-22

(0 records)

    [044/60] 2025-09-22 → 2025-10-06

(0 records)

    [045/60] 2025-10-06 → 2025-10-20

(0 records)

    [046/60] 2025-10-20 → 2025-11-03

(0 records)

    [047/60] 2025-11-03 → 2025-11-17

(0 records)

    [048/60] 2025-11-17 → 2025-12-01

(0 records)

    [049/60] 2025-12-01 → 2025-12-15

(0 records)

    [050/60] 2025-12-15 → 2025-12-29

(0 records)

    [051/60] 2025-12-29 → 2026-01-12

(0 records)

    [052/60] 2026-01-12 → 2026-01-26

(12 records)

    [053/60] 2026-01-26 → 2026-02-09

(12 records)

    [054/60] 2026-02-09 → 2026-02-23

(131 records)

    [055/60] 2026-02-23 → 2026-03-09

(62 records)

    [056/60] 2026-03-09 → 2026-03-23

(85 records)

    [057/60] 2026-03-23 → 2026-04-06

(76 records)

    [058/60] 2026-04-06 → 2026-04-20

(186 records)

    [059/60] 2026-04-20 → 2026-05-04

(70 records)

    [060/60] 2026-05-04 → 2026-05-15

(131 records)

  no2 | sensor=7772100 | 60 windows
    [001/60] 2024-01-29 → 2024-02-12

(280 records)

    [002/60] 2024-02-12 → 2024-02-26

(333 records)

    [003/60] 2024-02-26 → 2024-03-11

(296 records)

    [004/60] 2024-03-11 → 2024-03-25

(155 records)

    [005/60] 2024-03-25 → 2024-04-08

(123 records)

    [006/60] 2024-04-08 → 2024-04-22

(116 records)

    [007/60] 2024-04-22 → 2024-05-06

(75 records)

    [008/60] 2024-05-06 → 2024-05-20

(325 records)

    [009/60] 2024-05-20 → 2024-06-03

(141 records)

    [010/60] 2024-06-03 → 2024-06-17

(114 records)

    [011/60] 2024-06-17 → 2024-07-01

(109 records)

    [012/60] 2024-07-01 → 2024-07-15

(14 records)

    [013/60] 2024-07-15 → 2024-07-29

(0 records)

    [014/60] 2024-07-29 → 2024-08-12

(0 records)

    [015/60] 2024-08-12 → 2024-08-26

(0 records)

    [016/60] 2024-08-26 → 2024-09-09

(0 records)

    [017/60] 2024-09-09 → 2024-09-23

(0 records)

    [018/60] 2024-09-23 → 2024-10-07

(0 records)

    [019/60] 2024-10-07 → 2024-10-21

(0 records)

    [020/60] 2024-10-21 → 2024-11-04

(0 records)

    [021/60] 2024-11-04 → 2024-11-18

(0 records)

    [022/60] 2024-11-18 → 2024-12-02

(0 records)

    [023/60] 2024-12-02 → 2024-12-16

(0 records)

    [024/60] 2024-12-16 → 2024-12-30

(57 records)

    [025/60] 2024-12-30 → 2025-01-13

(0 records)

    [026/60] 2025-01-13 → 2025-01-27

(0 records)

    [027/60] 2025-01-27 → 2025-02-10

(0 records)

    [028/60] 2025-02-10 → 2025-02-24

(0 records)

    [029/60] 2025-02-24 → 2025-03-10

(0 records)

    [030/60] 2025-03-10 → 2025-03-24

(0 records)

    [031/60] 2025-03-24 → 2025-04-07

(0 records)

    [032/60] 2025-04-07 → 2025-04-21

(0 records)

    [033/60] 2025-04-21 → 2025-05-05

(0 records)

    [034/60] 2025-05-05 → 2025-05-19

(0 records)

    [035/60] 2025-05-19 → 2025-06-02

(0 records)

    [036/60] 2025-06-02 → 2025-06-16

(0 records)

    [037/60] 2025-06-16 → 2025-06-30

(0 records)

    [038/60] 2025-06-30 → 2025-07-14

(0 records)

    [039/60] 2025-07-14 → 2025-07-28

(0 records)

    [040/60] 2025-07-28 → 2025-08-11

(0 records)

    [041/60] 2025-08-11 → 2025-08-25

(0 records)

    [042/60] 2025-08-25 → 2025-09-08

(0 records)

    [043/60] 2025-09-08 → 2025-09-22

(0 records)

    [044/60] 2025-09-22 → 2025-10-06

(0 records)

    [045/60] 2025-10-06 → 2025-10-20

(0 records)

    [046/60] 2025-10-20 → 2025-11-03

(0 records)

    [047/60] 2025-11-03 → 2025-11-17

(0 records)

    [048/60] 2025-11-17 → 2025-12-01

(0 records)

    [049/60] 2025-12-01 → 2025-12-15

(0 records)

    [050/60] 2025-12-15 → 2025-12-29

(0 records)

    [051/60] 2025-12-29 → 2026-01-12

(0 records)

    [052/60] 2026-01-12 → 2026-01-26

(12 records)

    [053/60] 2026-01-26 → 2026-02-09

(12 records)

    [054/60] 2026-02-09 → 2026-02-23

(131 records)

    [055/60] 2026-02-23 → 2026-03-09

(62 records)

    [056/60] 2026-03-09 → 2026-03-23

(85 records)

    [057/60] 2026-03-23 → 2026-04-06

(76 records)

    [058/60] 2026-04-06 → 2026-04-20

(27 records)

    [059/60] 2026-04-20 → 2026-05-04

(0 records)

    [060/60] 2026-05-04 → 2026-05-15

(0 records)

  o3 | sensor=7772097 | 60 windows
    [001/60] 2024-01-29 → 2024-02-12

(280 records)

    [002/60] 2024-02-12 → 2024-02-26

(334 records)

    [003/60] 2024-02-26 → 2024-03-11

(299 records)

    [004/60] 2024-03-11 → 2024-03-25

(155 records)

    [005/60] 2024-03-25 → 2024-04-08

(132 records)

    [006/60] 2024-04-08 → 2024-04-22

(95 records)

    [007/60] 2024-04-22 → 2024-05-06

(72 records)

    [008/60] 2024-05-06 → 2024-05-20

(304 records)

    [009/60] 2024-05-20 → 2024-06-03

(139 records)

    [010/60] 2024-06-03 → 2024-06-17

(136 records)

    [011/60] 2024-06-17 → 2024-07-01

(143 records)

    [012/60] 2024-07-01 → 2024-07-15

(83 records)

    [013/60] 2024-07-15 → 2024-07-29

(234 records)

    [014/60] 2024-07-29 → 2024-08-12

(208 records)

    [015/60] 2024-08-12 → 2024-08-26

(7 records)

    [016/60] 2024-08-26 → 2024-09-09

(40 records)

    [017/60] 2024-09-09 → 2024-09-23

(65 records)

    [018/60] 2024-09-23 → 2024-10-07

(28 records)

    [019/60] 2024-10-07 → 2024-10-21

(21 records)

    [020/60] 2024-10-21 → 2024-11-04

(124 records)

    [021/60] 2024-11-04 → 2024-11-18

(83 records)

    [022/60] 2024-11-18 → 2024-12-02

(50 records)

    [023/60] 2024-12-02 → 2024-12-16

(0 records)

    [024/60] 2024-12-16 → 2024-12-30

(1 records)

    [025/60] 2024-12-30 → 2025-01-13

(25 records)

    [026/60] 2025-01-13 → 2025-01-27

(19 records)

    [027/60] 2025-01-27 → 2025-02-10

(133 records)

    [028/60] 2025-02-10 → 2025-02-24

(336 records)

    [029/60] 2025-02-24 → 2025-03-10

(334 records)

    [030/60] 2025-03-10 → 2025-03-24

(336 records)

    [031/60] 2025-03-24 → 2025-04-07

(335 records)

    [032/60] 2025-04-07 → 2025-04-21

(335 records)

    [033/60] 2025-04-21 → 2025-05-05

(147 records)

    [034/60] 2025-05-05 → 2025-05-19

(334 records)

    [035/60] 2025-05-19 → 2025-06-02

(329 records)

    [036/60] 2025-06-02 → 2025-06-16

(317 records)

    [037/60] 2025-06-16 → 2025-06-30

(208 records)

    [038/60] 2025-06-30 → 2025-07-14

(318 records)

    [039/60] 2025-07-14 → 2025-07-28

(301 records)

    [040/60] 2025-07-28 → 2025-08-11

(335 records)

    [041/60] 2025-08-11 → 2025-08-25

(69 records)

    [042/60] 2025-08-25 → 2025-09-08

(0 records)

    [043/60] 2025-09-08 → 2025-09-22

(0 records)

    [044/60] 2025-09-22 → 2025-10-06

(0 records)

    [045/60] 2025-10-06 → 2025-10-20

(0 records)

    [046/60] 2025-10-20 → 2025-11-03

(0 records)

    [047/60] 2025-11-03 → 2025-11-17

(0 records)

    [048/60] 2025-11-17 → 2025-12-01

(0 records)

    [049/60] 2025-12-01 → 2025-12-15

(0 records)

    [050/60] 2025-12-15 → 2025-12-29

(0 records)

    [051/60] 2025-12-29 → 2026-01-12

(0 records)

    [052/60] 2026-01-12 → 2026-01-26

(12 records)

    [053/60] 2026-01-26 → 2026-02-09

(12 records)

    [054/60] 2026-02-09 → 2026-02-23

(131 records)

    [055/60] 2026-02-23 → 2026-03-09

(62 records)

    [056/60] 2026-03-09 → 2026-03-23

(85 records)

    [057/60] 2026-03-23 → 2026-04-06

(76 records)

    [058/60] 2026-04-06 → 2026-04-20

(186 records)

    [059/60] 2026-04-20 → 2026-05-04

(70 records)

    [060/60] 2026-05-04 → 2026-05-15

(131 records)

  pm25 | sensor=7772087 | 60 windows
    [001/60] 2024-01-29 → 2024-02-12

(280 records)

    [002/60] 2024-02-12 → 2024-02-26

(333 records)

    [003/60] 2024-02-26 → 2024-03-11

(299 records)

    [004/60] 2024-03-11 → 2024-03-25

(134 records)

    [005/60] 2024-03-25 → 2024-04-08

(127 records)

    [006/60] 2024-04-08 → 2024-04-22

(143 records)

    [007/60] 2024-04-22 → 2024-05-06

(76 records)

    [008/60] 2024-05-06 → 2024-05-20

(325 records)

    [009/60] 2024-05-20 → 2024-06-03

(145 records)

    [010/60] 2024-06-03 → 2024-06-17

(145 records)

    [011/60] 2024-06-17 → 2024-07-01

(126 records)

    [012/60] 2024-07-01 → 2024-07-15

(67 records)

    [013/60] 2024-07-15 → 2024-07-29

(236 records)

    [014/60] 2024-07-29 → 2024-08-12

(237 records)

    [015/60] 2024-08-12 → 2024-08-26

(85 records)

    [016/60] 2024-08-26 → 2024-09-09

(72 records)

    [017/60] 2024-09-09 → 2024-09-23

(123 records)

    [018/60] 2024-09-23 → 2024-10-07

(31 records)

    [019/60] 2024-10-07 → 2024-10-21

(146 records)

    [020/60] 2024-10-21 → 2024-11-04

(248 records)

    [021/60] 2024-11-04 → 2024-11-18

(178 records)

    [022/60] 2024-11-18 → 2024-12-02

(237 records)

    [023/60] 2024-12-02 → 2024-12-16

(281 records)

    [024/60] 2024-12-16 → 2024-12-30

(290 records)

    [025/60] 2024-12-30 → 2025-01-13

(247 records)

    [026/60] 2025-01-13 → 2025-01-27

(33 records)

    [027/60] 2025-01-27 → 2025-02-10

(134 records)

    [028/60] 2025-02-10 → 2025-02-24

(123 records)

    [029/60] 2025-02-24 → 2025-03-10

(3 records)

    [030/60] 2025-03-10 → 2025-03-24

(0 records)

    [031/60] 2025-03-24 → 2025-04-07

(243 records)

    [032/60] 2025-04-07 → 2025-04-21

(331 records)

    [033/60] 2025-04-21 → 2025-05-05

(156 records)

    [034/60] 2025-05-05 → 2025-05-19

(319 records)

    [035/60] 2025-05-19 → 2025-06-02

(88 records)

    [036/60] 2025-06-02 → 2025-06-16

(0 records)

    [037/60] 2025-06-16 → 2025-06-30

(0 records)

    [038/60] 2025-06-30 → 2025-07-14

(0 records)

    [039/60] 2025-07-14 → 2025-07-28

(0 records)

    [040/60] 2025-07-28 → 2025-08-11

(85 records)

    [041/60] 2025-08-11 → 2025-08-25

(50 records)

    [042/60] 2025-08-25 → 2025-09-08

(0 records)

    [043/60] 2025-09-08 → 2025-09-22

(0 records)

    [044/60] 2025-09-22 → 2025-10-06

(0 records)

    [045/60] 2025-10-06 → 2025-10-20

(0 records)

    [046/60] 2025-10-20 → 2025-11-03

(0 records)

    [047/60] 2025-11-03 → 2025-11-17

(0 records)

    [048/60] 2025-11-17 → 2025-12-01

(0 records)

    [049/60] 2025-12-01 → 2025-12-15

(0 records)

    [050/60] 2025-12-15 → 2025-12-29

(0 records)

    [051/60] 2025-12-29 → 2026-01-12

(0 records)

    [052/60] 2026-01-12 → 2026-01-26

(12 records)

    [053/60] 2026-01-26 → 2026-02-09

(12 records)

    [054/60] 2026-02-09 → 2026-02-23

(131 records)

    [055/60] 2026-02-23 → 2026-03-09

(62 records)

    [056/60] 2026-03-09 → 2026-03-23

(85 records)

    [057/60] 2026-03-23 → 2026-04-06

(76 records)

    [058/60] 2026-04-06 → 2026-04-20

(100 records)

    [059/60] 2026-04-20 → 2026-05-04

(39 records)

    [060/60] 2026-05-04 → 2026-05-15

(124 records)

  so2 | sensor=7772047 | 60 windows
    [001/60] 2024-01-29 → 2024-02-12

(280 records)

    [002/60] 2024-02-12 → 2024-02-26

(333 records)

    [003/60] 2024-02-26 → 2024-03-11

(292 records)

    [004/60] 2024-03-11 → 2024-03-25

(155 records)

    [005/60] 2024-03-25 → 2024-04-08

(133 records)

    [006/60] 2024-04-08 → 2024-04-22

(55 records)

    [007/60] 2024-04-22 → 2024-05-06

(46 records)

    [008/60] 2024-05-06 → 2024-05-20

(169 records)

    [009/60] 2024-05-20 → 2024-06-03

(65 records)

    [010/60] 2024-06-03 → 2024-06-17

(11 records)

    [011/60] 2024-06-17 → 2024-07-01

(3 records)

    [012/60] 2024-07-01 → 2024-07-15

(0 records)

    [013/60] 2024-07-15 → 2024-07-29

(0 records)

    [014/60] 2024-07-29 → 2024-08-12

(28 records)

    [015/60] 2024-08-12 → 2024-08-26

(4 records)

    [016/60] 2024-08-26 → 2024-09-09

(0 records)

    [017/60] 2024-09-09 → 2024-09-23

(14 records)

    [018/60] 2024-09-23 → 2024-10-07

(6 records)

    [019/60] 2024-10-07 → 2024-10-21

(1 records)

    [020/60] 2024-10-21 → 2024-11-04

(23 records)

    [021/60] 2024-11-04 → 2024-11-18

(5 records)

    [022/60] 2024-11-18 → 2024-12-02

(3 records)

    [023/60] 2024-12-02 → 2024-12-16

(0 records)

    [024/60] 2024-12-16 → 2024-12-30

(0 records)

    [025/60] 2024-12-30 → 2025-01-13

(26 records)

    [026/60] 2025-01-13 → 2025-01-27

(26 records)

    [027/60] 2025-01-27 → 2025-02-10

(156 records)

    [028/60] 2025-02-10 → 2025-02-24

(336 records)

    [029/60] 2025-02-24 → 2025-03-10

(334 records)

    [030/60] 2025-03-10 → 2025-03-24

(265 records)

    [031/60] 2025-03-24 → 2025-04-07

(252 records)

    [032/60] 2025-04-07 → 2025-04-21

(335 records)

    [033/60] 2025-04-21 → 2025-05-05

(158 records)

    [034/60] 2025-05-05 → 2025-05-19

(334 records)

    [035/60] 2025-05-19 → 2025-06-02

(329 records)

    [036/60] 2025-06-02 → 2025-06-16

(246 records)

    [037/60] 2025-06-16 → 2025-06-30

(0 records)

    [038/60] 2025-06-30 → 2025-07-14

(0 records)

    [039/60] 2025-07-14 → 2025-07-28

(0 records)

    [040/60] 2025-07-28 → 2025-08-11

(0 records)

    [041/60] 2025-08-11 → 2025-08-25

(0 records)

    [042/60] 2025-08-25 → 2025-09-08

(0 records)

    [043/60] 2025-09-08 → 2025-09-22

(0 records)

    [044/60] 2025-09-22 → 2025-10-06

(0 records)

    [045/60] 2025-10-06 → 2025-10-20

(0 records)

    [046/60] 2025-10-20 → 2025-11-03

(0 records)

    [047/60] 2025-11-03 → 2025-11-17

(0 records)

    [048/60] 2025-11-17 → 2025-12-01

(0 records)

    [049/60] 2025-12-01 → 2025-12-15

(0 records)

    [050/60] 2025-12-15 → 2025-12-29

(0 records)

    [051/60] 2025-12-29 → 2026-01-12

(0 records)

    [052/60] 2026-01-12 → 2026-01-26

(12 records)

    [053/60] 2026-01-26 → 2026-02-09

(12 records)

    [054/60] 2026-02-09 → 2026-02-23

(131 records)

    [055/60] 2026-02-23 → 2026-03-09

(62 records)

    [056/60] 2026-03-09 → 2026-03-23

(85 records)

    [057/60] 2026-03-23 → 2026-04-06

(76 records)

    [058/60] 2026-04-06 → 2026-04-20

(186 records)

    [059/60] 2026-04-20 → 2026-05-04

(70 records)

    [060/60] 2026-05-04 → 2026-05-15

(0 records)

  Saved: 2161306_Minh Khai - Bắc Từ Liêm.csv  shape=(9847, 10)
  PM2.5 rows: 6792

============================================================
Station 2161307: Mỹ Đình
  Range: 2021-01-01  →  2026-05-15

  Sensors: 3
  co | sensor=7772063 | 1 windows
    [001/1] 2024-01-28 → 2024-01-30

(11 records)

  no2 | sensor=7772108 | 1 windows
    [001/1] 2024-01-28 → 2024-01-30

(11 records)

  pm25 | sensor=7771998 | 1 windows
    [001/1] 2024-01-28 → 2024-01-30

(11 records)

  Saved: 2161307_Mỹ Đình.csv  shape=(11, 10)
  PM2.5 rows: 11

============================================================
Station 2161308: Phạm Văn Đồng
  Range: 2021-01-01  →  2026-05-15

  Sensors: 3
  co | sensor=7772051 | 1 windows
    [001/1] 2024-01-22 → 2024-01-22

(1 records)

  no2 | sensor=7772056 | 1 windows
    [001/1] 2024-01-22 → 2024-01-22

(1 records)

  pm25 | sensor=7772088 | 1 windows
    [001/1] 2024-01-22 → 2024-01-22

(1 records)

  Saved: 2161308_Phạm Văn Đồng.csv  shape=(1, 10)
  PM2.5 rows: 1

============================================================
Station 2161309: Pháp Vân
  Range: 2021-01-01  →  2026-05-15

  Sensors: 3
  co | sensor=7772084 | 27 windows
    [001/27] 2024-01-29 → 2024-02-12

(280 records)

    [002/27] 2024-02-12 → 2024-02-26

(307 records)

    [003/27] 2024-02-26 → 2024-03-11

(233 records)

    [004/27] 2024-03-11 → 2024-03-25

(153 records)

    [005/27] 2024-03-25 → 2024-04-08

(243 records)

    [006/27] 2024-04-08 → 2024-04-22

(97 records)

    [007/27] 2024-04-22 → 2024-05-06

(228 records)

    [008/27] 2024-05-06 → 2024-05-20

(313 records)

    [009/27] 2024-05-20 → 2024-06-03

(175 records)

    [010/27] 2024-06-03 → 2024-06-17

(324 records)

    [011/27] 2024-06-17 → 2024-07-01

(326 records)

    [012/27] 2024-07-01 → 2024-07-15

(318 records)

    [013/27] 2024-07-15 → 2024-07-29

(263 records)

    [014/27] 2024-07-29 → 2024-08-12

(319 records)

    [015/27] 2024-08-12 → 2024-08-26

(152 records)

    [016/27] 2024-08-26 → 2024-09-09

(81 records)

    [017/27] 2024-09-09 → 2024-09-23

(0 records)

    [018/27] 2024-09-23 → 2024-10-07

(138 records)

    [019/27] 2024-10-07 → 2024-10-21

(322 records)

    [020/27] 2024-10-21 → 2024-11-04

(319 records)

    [021/27] 2024-11-04 → 2024-11-18

(303 records)

    [022/27] 2024-11-18 → 2024-12-02

(326 records)

    [023/27] 2024-12-02 → 2024-12-16

(259 records)

    [024/27] 2024-12-16 → 2024-12-30

(336 records)

    [025/27] 2024-12-30 → 2025-01-13

(330 records)

    [026/27] 2025-01-13 → 2025-01-27

(318 records)

    [027/27] 2025-01-27 → 2025-02-05

(213 records)

  no2 | sensor=7772091 | 27 windows
    [001/27] 2024-01-29 → 2024-02-12

(283 records)

    [002/27] 2024-02-12 → 2024-02-26

(311 records)

    [003/27] 2024-02-26 → 2024-03-11

(233 records)

    [004/27] 2024-03-11 → 2024-03-25

(153 records)

    [005/27] 2024-03-25 → 2024-04-08

(245 records)

    [006/27] 2024-04-08 → 2024-04-22

(100 records)

    [007/27] 2024-04-22 → 2024-05-06

(236 records)

    [008/27] 2024-05-06 → 2024-05-20

(328 records)

    [009/27] 2024-05-20 → 2024-06-03

(178 records)

    [010/27] 2024-06-03 → 2024-06-17

(336 records)

    [011/27] 2024-06-17 → 2024-07-01

(334 records)

    [012/27] 2024-07-01 → 2024-07-15

(332 records)

    [013/27] 2024-07-15 → 2024-07-29

(274 records)

    [014/27] 2024-07-29 → 2024-08-12

(336 records)

    [015/27] 2024-08-12 → 2024-08-26

(163 records)

    [016/27] 2024-08-26 → 2024-09-09

(85 records)

    [017/27] 2024-09-09 → 2024-09-23

(0 records)

    [018/27] 2024-09-23 → 2024-10-07

(146 records)

    [019/27] 2024-10-07 → 2024-10-21

(328 records)

    [020/27] 2024-10-21 → 2024-11-04

(331 records)

    [021/27] 2024-11-04 → 2024-11-18

(309 records)

    [022/27] 2024-11-18 → 2024-12-02

(336 records)

    [023/27] 2024-12-02 → 2024-12-16

(262 records)

    [024/27] 2024-12-16 → 2024-12-30

(336 records)

    [025/27] 2024-12-30 → 2025-01-13

(330 records)

    [026/27] 2025-01-13 → 2025-01-27

(318 records)

    [027/27] 2025-01-27 → 2025-02-05

(213 records)

  pm25 | sensor=7772016 | 27 windows
    [001/27] 2024-01-29 → 2024-02-12

(283 records)

    [002/27] 2024-02-12 → 2024-02-26

(311 records)

    [003/27] 2024-02-26 → 2024-03-11

(233 records)

    [004/27] 2024-03-11 → 2024-03-25

(153 records)

    [005/27] 2024-03-25 → 2024-04-08

(244 records)

    [006/27] 2024-04-08 → 2024-04-22

(99 records)

    [007/27] 2024-04-22 → 2024-05-06

(236 records)

    [008/27] 2024-05-06 → 2024-05-20

(328 records)

    [009/27] 2024-05-20 → 2024-06-03

(178 records)

    [010/27] 2024-06-03 → 2024-06-17

(336 records)

    [011/27] 2024-06-17 → 2024-07-01

(334 records)

    [012/27] 2024-07-01 → 2024-07-15

(332 records)

    [013/27] 2024-07-15 → 2024-07-29

(274 records)

    [014/27] 2024-07-29 → 2024-08-12

(336 records)

    [015/27] 2024-08-12 → 2024-08-26

(163 records)

    [016/27] 2024-08-26 → 2024-09-09

(85 records)

    [017/27] 2024-09-09 → 2024-09-23

(0 records)

    [018/27] 2024-09-23 → 2024-10-07

(146 records)

    [019/27] 2024-10-07 → 2024-10-21

(329 records)

    [020/27] 2024-10-21 → 2024-11-04

(331 records)

    [021/27] 2024-11-04 → 2024-11-18

(309 records)

    [022/27] 2024-11-18 → 2024-12-02

(336 records)

    [023/27] 2024-12-02 → 2024-12-16

(255 records)

    [024/27] 2024-12-16 → 2024-12-30

(336 records)

    [025/27] 2024-12-30 → 2025-01-13

(330 records)

    [026/27] 2025-01-13 → 2025-01-27

(318 records)

    [027/27] 2025-01-27 → 2025-02-05

(213 records)

  Saved: 2161309_Pháp Vân.csv  shape=(6837, 10)
  PM2.5 rows: 6828

============================================================
Station 2161313: Tân Mai
  Range: 2021-01-01  →  2026-05-15

  Sensors: 3
  co | sensor=7772094 | 3 windows
    [001/3] 2024-01-29 → 2024-02-12

(94 records)

    [002/3] 2024-02-12 → 2024-02-26

(129 records)

    [003/3] 2024-02-26 → 2024-03-01

(80 records)

  no2 | sensor=7772098 | 3 windows
    [001/3] 2024-01-29 → 2024-02-12

(94 records)

    [002/3] 2024-02-12 → 2024-02-26

(129 records)

    [003/3] 2024-02-26 → 2024-03-01

(80 records)

  pm25 | sensor=7772003 | 3 windows
    [001/3] 2024-01-29 → 2024-02-12

(90 records)

    [002/3] 2024-02-12 → 2024-02-26

(116 records)

    [003/3] 2024-02-26 → 2024-03-01

(74 records)

  Saved: 2161313_Tân Mai.csv  shape=(303, 10)
  PM2.5 rows: 280

============================================================
Station 2161314: Tây Hồ Tây
  Range: 2021-01-01  →  2026-05-15

  Sensors: 3
  co | sensor=7772054 | 4 windows
    [001/4] 2024-01-29 → 2024-02-12

(86 records)

    [002/4] 2024-02-12 → 2024-02-26

(129 records)

    [003/4] 2024-02-26 → 2024-03-11

(236 records)

    [004/4] 2024-03-11 → 2024-03-22

(111 records)

  no2 | sensor=7772066 | 4 windows
    [001/4] 2024-01-29 → 2024-02-12

(86 records)

    [002/4] 2024-02-12 → 2024-02-26

(129 records)

    [003/4] 2024-02-26 → 2024-03-11

(236 records)

    [004/4] 2024-03-11 → 2024-03-22

(112 records)

  pm25 | sensor=7771972 | 4 windows
    [001/4] 2024-01-29 → 2024-02-12

(86 records)

    [002/4] 2024-02-12 → 2024-02-26

(125 records)

    [003/4] 2024-02-26 → 2024-03-11

(220 records)

    [004/4] 2024-03-11 → 2024-03-22

(111 records)

  Saved: 2161314_Tây Hồ Tây.csv  shape=(563, 10)
  PM2.5 rows: 542

============================================================
Station 2161315: Tây Mỗ
  Range: 2021-01-01  →  2026-05-15

  Sensors: 3
  co | sensor=7772072 | 1 windows
    [001/1] 2024-01-29 → 2024-02-06

(49 records)

  no2 | sensor=7772002 | 1 windows
    [001/1] 2024-01-29 → 2024-02-06

(49 records)

  pm25 | sensor=7772004 | 1 windows
    [001/1] 2024-01-29 → 2024-02-07

(51 records)

  Saved: 2161315_Tây Mỗ.csv  shape=(52, 10)
  PM2.5 rows: 51

============================================================
Station 2161316: Thành Công
  Range: 2021-01-01  →  2026-05-15

  Sensors: 3
  co | sensor=7772078 | 3 windows
    [001/3] 2024-01-29 → 2024-02-12

(86 records)

    [002/3] 2024-02-12 → 2024-02-26

(119 records)

    [003/3] 2024-02-26 → 2024-02-27

(14 records)

  no2 | sensor=7772007 | 3 windows
    [001/3] 2024-01-29 → 2024-02-12

(86 records)

    [002/3] 2024-02-12 → 2024-02-26

(120 records)

    [003/3] 2024-02-26 → 2024-02-27

(14 records)

  pm25 | sensor=7772020 | 3 windows
    [001/3] 2024-01-29 → 2024-02-12

(86 records)

    [002/3] 2024-02-12 → 2024-02-26

(120 records)

    [003/3] 2024-02-26 → 2024-02-27

(14 records)

  Saved: 2161316_Thành Công.csv  shape=(220, 10)
  PM2.5 rows: 220

============================================================
Station 2161318: Tứ Liên
  Range: 2021-01-01  →  2026-05-15

  Sensors: 3
  co | sensor=7772074 | 4 windows
    [001/4] 2024-01-29 → 2024-02-12

(94 records)

    [002/4] 2024-02-12 → 2024-02-26

(129 records)

    [003/4] 2024-02-26 → 2024-03-11

(236 records)

    [004/4] 2024-03-11 → 2024-03-22

(111 records)

  no2 | sensor=7772070 | 4 windows
    [001/4] 2024-01-29 → 2024-02-12

(94 records)

    [002/4] 2024-02-12 → 2024-02-26

(129 records)

    [003/4] 2024-02-26 → 2024-03-11

(236 records)

    [004/4] 2024-03-11 → 2024-03-22

(111 records)

  pm25 | sensor=7772036 | 4 windows
    [001/4] 2024-01-29 → 2024-02-12

(92 records)

    [002/4] 2024-02-12 → 2024-02-26

(120 records)

    [003/4] 2024-02-26 → 2024-03-11

(227 records)

    [004/4] 2024-03-11 → 2024-03-22

(111 records)

  Saved: 2161318_Tứ Liên.csv  shape=(574, 10)
  PM2.5 rows: 550

============================================================
Station 2161320: Vân Hà
  Range: 2021-01-01  →  2026-05-15

  Sensors: 3
  co | sensor=7772041 | 36 windows
    [001/36] 2024-01-29 → 2024-02-12

(296 records)

    [002/36] 2024-02-12 → 2024-02-26

(336 records)

    [003/36] 2024-02-26 → 2024-03-11

(317 records)

    [004/36] 2024-03-11 → 2024-03-25

(232 records)

    [005/36] 2024-03-25 → 2024-04-08

(336 records)

    [006/36] 2024-04-08 → 2024-04-22

(279 records)

    [007/36] 2024-04-22 → 2024-05-06

(246 records)

    [008/36] 2024-05-06 → 2024-05-20

(329 records)

    [009/36] 2024-05-20 → 2024-06-03

(178 records)

    [010/36] 2024-06-03 → 2024-06-17

(164 records)

    [011/36] 2024-06-17 → 2024-07-01

(215 records)

    [012/36] 2024-07-01 → 2024-07-15

(336 records)

    [013/36] 2024-07-15 → 2024-07-29

(283 records)

    [014/36] 2024-07-29 → 2024-08-12

(328 records)

    [015/36] 2024-08-12 → 2024-08-26

(156 records)

    [016/36] 2024-08-26 → 2024-09-09

(188 records)

    [017/36] 2024-09-09 → 2024-09-23

(336 records)

    [018/36] 2024-09-23 → 2024-10-07

(335 records)

    [019/36] 2024-10-07 → 2024-10-21

(329 records)

    [020/36] 2024-10-21 → 2024-11-04

(331 records)

    [021/36] 2024-11-04 → 2024-11-18

(309 records)

    [022/36] 2024-11-18 → 2024-12-02

(336 records)

    [023/36] 2024-12-02 → 2024-12-16

(334 records)

    [024/36] 2024-12-16 → 2024-12-30

(321 records)

    [025/36] 2024-12-30 → 2025-01-13

(330 records)

    [026/36] 2025-01-13 → 2025-01-27

(318 records)

    [027/36] 2025-01-27 → 2025-02-10

(276 records)

    [028/36] 2025-02-10 → 2025-02-24

(336 records)

    [029/36] 2025-02-24 → 2025-03-10

(336 records)

    [030/36] 2025-03-10 → 2025-03-24

(336 records)

    [031/36] 2025-03-24 → 2025-04-07

(336 records)

    [032/36] 2025-04-07 → 2025-04-21

(335 records)

    [033/36] 2025-04-21 → 2025-05-05

(233 records)

    [034/36] 2025-05-05 → 2025-05-19

(336 records)

    [035/36] 2025-05-19 → 2025-06-02

(329 records)

    [036/36] 2025-06-02 → 2025-06-10

(180 records)

  no2 | sensor=7771986 | 36 windows
    [001/36] 2024-01-29 → 2024-02-12

(296 records)

    [002/36] 2024-02-12 → 2024-02-26

(336 records)

    [003/36] 2024-02-26 → 2024-03-11

(317 records)

    [004/36] 2024-03-11 → 2024-03-25

(232 records)

    [005/36] 2024-03-25 → 2024-04-08

(336 records)

    [006/36] 2024-04-08 → 2024-04-22

(279 records)

    [007/36] 2024-04-22 → 2024-05-06

(246 records)

    [008/36] 2024-05-06 → 2024-05-20

(329 records)

    [009/36] 2024-05-20 → 2024-06-03

(178 records)

    [010/36] 2024-06-03 → 2024-06-17

(164 records)

    [011/36] 2024-06-17 → 2024-07-01

(215 records)

    [012/36] 2024-07-01 → 2024-07-15

(336 records)

    [013/36] 2024-07-15 → 2024-07-29

(283 records)

    [014/36] 2024-07-29 → 2024-08-12

(329 records)

    [015/36] 2024-08-12 → 2024-08-26

(156 records)

    [016/36] 2024-08-26 → 2024-09-09

(189 records)

    [017/36] 2024-09-09 → 2024-09-23

(336 records)

    [018/36] 2024-09-23 → 2024-10-07

(335 records)

    [019/36] 2024-10-07 → 2024-10-21

(329 records)

    [020/36] 2024-10-21 → 2024-11-04

(331 records)

    [021/36] 2024-11-04 → 2024-11-18

(309 records)

    [022/36] 2024-11-18 → 2024-12-02

(336 records)

    [023/36] 2024-12-02 → 2024-12-16

(336 records)

    [024/36] 2024-12-16 → 2024-12-30

(321 records)

    [025/36] 2024-12-30 → 2025-01-13

(330 records)

    [026/36] 2025-01-13 → 2025-01-27

(318 records)

    [027/36] 2025-01-27 → 2025-02-10

(276 records)

    [028/36] 2025-02-10 → 2025-02-24

(336 records)

    [029/36] 2025-02-24 → 2025-03-10

(336 records)

    [030/36] 2025-03-10 → 2025-03-24

(336 records)

    [031/36] 2025-03-24 → 2025-04-07

(336 records)

    [032/36] 2025-04-07 → 2025-04-21

(335 records)

    [033/36] 2025-04-21 → 2025-05-05

(234 records)

    [034/36] 2025-05-05 → 2025-05-19

(336 records)

    [035/36] 2025-05-19 → 2025-06-02

(329 records)

    [036/36] 2025-06-02 → 2025-06-10

(180 records)

  pm25 | sensor=7772059 | 36 windows
    [001/36] 2024-01-29 → 2024-02-12

(296 records)

    [002/36] 2024-02-12 → 2024-02-26

(336 records)

    [003/36] 2024-02-26 → 2024-03-11

(317 records)

    [004/36] 2024-03-11 → 2024-03-25

(232 records)

    [005/36] 2024-03-25 → 2024-04-08

(336 records)

    [006/36] 2024-04-08 → 2024-04-22

(279 records)

    [007/36] 2024-04-22 → 2024-05-06

(246 records)

    [008/36] 2024-05-06 → 2024-05-20

(329 records)

    [009/36] 2024-05-20 → 2024-06-03

(178 records)

    [010/36] 2024-06-03 → 2024-06-17

(164 records)

    [011/36] 2024-06-17 → 2024-07-01

(215 records)

    [012/36] 2024-07-01 → 2024-07-15

(336 records)

    [013/36] 2024-07-15 → 2024-07-29

(283 records)

    [014/36] 2024-07-29 → 2024-08-12

(329 records)

    [015/36] 2024-08-12 → 2024-08-26

(156 records)

    [016/36] 2024-08-26 → 2024-09-09

(190 records)

    [017/36] 2024-09-09 → 2024-09-23

(336 records)

    [018/36] 2024-09-23 → 2024-10-07

(335 records)

    [019/36] 2024-10-07 → 2024-10-21

(329 records)

    [020/36] 2024-10-21 → 2024-11-04

(331 records)

    [021/36] 2024-11-04 → 2024-11-18

(309 records)

    [022/36] 2024-11-18 → 2024-12-02

(336 records)

    [023/36] 2024-12-02 → 2024-12-16

(326 records)

    [024/36] 2024-12-16 → 2024-12-30

(321 records)

    [025/36] 2024-12-30 → 2025-01-13

(330 records)

    [026/36] 2025-01-13 → 2025-01-27

(318 records)

    [027/36] 2025-01-27 → 2025-02-10

(276 records)

    [028/36] 2025-02-10 → 2025-02-24

(336 records)

    [029/36] 2025-02-24 → 2025-03-10

(336 records)

    [030/36] 2025-03-10 → 2025-03-24

(336 records)

    [031/36] 2025-03-24 → 2025-04-07

(336 records)

    [032/36] 2025-04-07 → 2025-04-21

(335 records)

    [033/36] 2025-04-21 → 2025-05-05

(233 records)

    [034/36] 2025-05-05 → 2025-05-19

(336 records)

    [035/36] 2025-05-19 → 2025-06-02

(329 records)

    [036/36] 2025-06-02 → 2025-06-10

(180 records)

  Saved: 2161320_Vân Hà.csv  shape=(10546, 10)
  PM2.5 rows: 10526

============================================================
Station 2161321: Văn Quán
  Range: 2021-01-01  →  2026-05-15

  Sensors: 3
  co | sensor=7771990 | 5 windows
    [001/5] 2024-01-29 → 2024-02-12

(94 records)

    [002/5] 2024-02-12 → 2024-02-26

(129 records)

    [003/5] 2024-02-26 → 2024-03-11

(236 records)

    [004/5] 2024-03-11 → 2024-03-25

(134 records)

    [005/5] 2024-03-25 → 2024-04-05

(168 records)

  no2 | sensor=7772028 | 5 windows
    [001/5] 2024-01-29 → 2024-02-12

(94 records)

    [002/5] 2024-02-12 → 2024-02-26

(129 records)

    [003/5] 2024-02-26 → 2024-03-11

(236 records)

    [004/5] 2024-03-11 → 2024-03-25

(134 records)

    [005/5] 2024-03-25 → 2024-04-05

(168 records)

  pm25 | sensor=7772099 | 5 windows
    [001/5] 2024-01-29 → 2024-02-12

(94 records)

    [002/5] 2024-02-12 → 2024-02-26

(128 records)

    [003/5] 2024-02-26 → 2024-03-11

(234 records)

    [004/5] 2024-03-11 → 2024-03-25

(134 records)

    [005/5] 2024-03-25 → 2024-04-05

(168 records)

  Saved: 2161321_Văn Quán.csv  shape=(761, 10)
  PM2.5 rows: 758

============================================================
Station 2161322: Võng La
  Range: 2021-01-01  →  2026-05-15

  Sensors: 3
  co | sensor=7771985 | 1 windows
    [001/1] 2024-01-15 → 2024-01-15

(1 records)

  no2 | sensor=7771989 | 1 windows
    [001/1] 2024-01-15 → 2024-01-15

(1 records)

  pm25 | sensor=7772079 | 1 windows
    [001/1] 2024-01-15 → 2024-01-15

(2 records)

  Saved: 2161322_Võng La.csv  shape=(2, 10)
  PM2.5 rows: 2

============================================================
Station 4946811: 556 Nguyễn Văn Cừ
  Range: 2021-01-01  →  2026-05-15

  Sensors: 5
  co | sensor=13502158 | 11 windows
    [001/11] 2025-07-03 → 2025-07-17

(336 records)

    [002/11] 2025-07-17 → 2025-07-31

(317 records)

    [003/11] 2025-07-31 → 2025-08-14

(332 records)

    [004/11] 2025-08-14 → 2025-08-28

(336 records)

    [005/11] 2025-08-28 → 2025-09-11

(334 records)

    [006/11] 2025-09-11 → 2025-09-25

(335 records)

    [007/11] 2025-09-25 → 2025-10-09

(311 records)

    [008/11] 2025-10-09 → 2025-10-23

(332 records)

    [009/11] 2025-10-23 → 2025-11-06

(335 records)

    [010/11] 2025-11-06 → 2025-11-20

(330 records)

    [011/11] 2025-11-20 → 2025-11-25

(121 records)

  no2 | sensor=13502159 | 19 windows
    [001/19] 2025-07-03 → 2025-07-17

(335 records)

    [002/19] 2025-07-17 → 2025-07-31

(317 records)

    [003/19] 2025-07-31 → 2025-08-14

(331 records)

    [004/19] 2025-08-14 → 2025-08-28

(203 records)

    [005/19] 2025-08-28 → 2025-09-11

(213 records)

    [006/19] 2025-09-11 → 2025-09-25

(335 records)

    [007/19] 2025-09-25 → 2025-10-09

(310 records)

    [008/19] 2025-10-09 → 2025-10-23

(332 records)

    [009/19] 2025-10-23 → 2025-11-06

(335 records)

    [010/19] 2025-11-06 → 2025-11-20

(236 records)

    [011/19] 2025-11-20 → 2025-12-04

(45 records)

    [012/19] 2025-12-04 → 2025-12-18

(34 records)

    [013/19] 2025-12-18 → 2026-01-01

(59 records)

    [014/19] 2026-01-01 → 2026-01-15

(46 records)

    [015/19] 2026-01-15 → 2026-01-29

(15 records)

    [016/19] 2026-01-29 → 2026-02-12

(0 records)

    [017/19] 2026-02-12 → 2026-02-26

(0 records)

    [018/19] 2026-02-26 → 2026-03-12

(179 records)

    [019/19] 2026-03-12 → 2026-03-25

(308 records)

  o3 | sensor=13502160 | 23 windows
    [001/23] 2025-07-03 → 2025-07-17

(333 records)

    [002/23] 2025-07-17 → 2025-07-31

(317 records)

    [003/23] 2025-07-31 → 2025-08-14

(332 records)

    [004/23] 2025-08-14 → 2025-08-28

(332 records)

    [005/23] 2025-08-28 → 2025-09-11

(334 records)

    [006/23] 2025-09-11 → 2025-09-25

(335 records)

    [007/23] 2025-09-25 → 2025-10-09

(310 records)

    [008/23] 2025-10-09 → 2025-10-23

(332 records)

    [009/23] 2025-10-23 → 2025-11-06

(11 records)

    [010/23] 2025-11-06 → 2025-11-20

(0 records)

    [011/23] 2025-11-20 → 2025-12-04

(143 records)

    [012/23] 2025-12-04 → 2025-12-18

(231 records)

    [013/23] 2025-12-18 → 2026-01-01

(336 records)

    [014/23] 2026-01-01 → 2026-01-15

(325 records)

    [015/23] 2026-01-15 → 2026-01-29

(321 records)

    [016/23] 2026-01-29 → 2026-02-12

(335 records)

    [017/23] 2026-02-12 → 2026-02-26

(328 records)

    [018/23] 2026-02-26 → 2026-03-12

(265 records)

    [019/23] 2026-03-12 → 2026-03-26

(336 records)

    [020/23] 2026-03-26 → 2026-04-09

(332 records)

    [021/23] 2026-04-09 → 2026-04-23

(336 records)

    [022/23] 2026-04-23 → 2026-05-07

(336 records)

    [023/23] 2026-05-07 → 2026-05-15

(164 records)

  pm25 | sensor=13502150 | 23 windows
    [001/23] 2025-07-03 → 2025-07-17

(328 records)

    [002/23] 2025-07-17 → 2025-07-31

(317 records)

    [003/23] 2025-07-31 → 2025-08-14

(330 records)

    [004/23] 2025-08-14 → 2025-08-28

(293 records)

    [005/23] 2025-08-28 → 2025-09-11

(333 records)

    [006/23] 2025-09-11 → 2025-09-25

(316 records)

    [007/23] 2025-09-25 → 2025-10-09

(309 records)

    [008/23] 2025-10-09 → 2025-10-23

(328 records)

    [009/23] 2025-10-23 → 2025-11-06

(323 records)

    [010/23] 2025-11-06 → 2025-11-20

(317 records)

    [011/23] 2025-11-20 → 2025-12-04

(292 records)

    [012/23] 2025-12-04 → 2025-12-18

(232 records)

    [013/23] 2025-12-18 → 2026-01-01

(336 records)

    [014/23] 2026-01-01 → 2026-01-15

(322 records)

    [015/23] 2026-01-15 → 2026-01-29

(314 records)

    [016/23] 2026-01-29 → 2026-02-12

(323 records)

    [017/23] 2026-02-12 → 2026-02-26

(336 records)

    [018/23] 2026-02-26 → 2026-03-12

(331 records)

    [019/23] 2026-03-12 → 2026-03-26

(336 records)

    [020/23] 2026-03-26 → 2026-04-09

(331 records)

    [021/23] 2026-04-09 → 2026-04-23

(335 records)

    [022/23] 2026-04-23 → 2026-05-07

(328 records)

    [023/23] 2026-05-07 → 2026-05-15

(161 records)

  so2 | sensor=13502161 | 23 windows
    [001/23] 2025-07-03 → 2025-07-17

(336 records)

    [002/23] 2025-07-17 → 2025-07-31

(317 records)

    [003/23] 2025-07-31 → 2025-08-14

(332 records)

    [004/23] 2025-08-14 → 2025-08-28

(336 records)

    [005/23] 2025-08-28 → 2025-09-11

(334 records)

    [006/23] 2025-09-11 → 2025-09-25

(335 records)

    [007/23] 2025-09-25 → 2025-10-09

(311 records)

    [008/23] 2025-10-09 → 2025-10-23

(332 records)

    [009/23] 2025-10-23 → 2025-11-06

(335 records)

    [010/23] 2025-11-06 → 2025-11-20

(330 records)

    [011/23] 2025-11-20 → 2025-12-04

(163 records)

    [012/23] 2025-12-04 → 2025-12-18

(2 records)

    [013/23] 2025-12-18 → 2026-01-01

(0 records)

    [014/23] 2026-01-01 → 2026-01-15

(0 records)

    [015/23] 2026-01-15 → 2026-01-29

(1 records)

    [016/23] 2026-01-29 → 2026-02-12

(0 records)

    [017/23] 2026-02-12 → 2026-02-26

(0 records)

    [018/23] 2026-02-26 → 2026-03-12

(176 records)

    [019/23] 2026-03-12 → 2026-03-26

(335 records)

    [020/23] 2026-03-26 → 2026-04-09

(332 records)

    [021/23] 2026-04-09 → 2026-04-23

(336 records)

    [022/23] 2026-04-23 → 2026-05-07

(336 records)

    [023/23] 2026-05-07 → 2026-05-15

(164 records)

  Saved: 4946811_556 Nguyễn Văn Cừ.csv  shape=(7327, 10)
  PM2.5 rows: 7171

============================================================
Station 4946812: Công viên Nhân Chính - Khuất Duy Tiến
  Range: 2021-01-01  →  2026-05-15

  Sensors: 5
  co | sensor=13502163 | 23 windows
    [001/23] 2025-07-03 → 2025-07-17

(336 records)

    [002/23] 2025-07-17 → 2025-07-31

(329 records)

    [003/23] 2025-07-31 → 2025-08-14

(332 records)

    [004/23] 2025-08-14 → 2025-08-28

(336 records)

    [005/23] 2025-08-28 → 2025-09-11

(334 records)

    [006/23] 2025-09-11 → 2025-09-25

(336 records)

    [007/23] 2025-09-25 → 2025-10-09

(304 records)

    [008/23] 2025-10-09 → 2025-10-23

(322 records)

    [009/23] 2025-10-23 → 2025-11-06

(335 records)

    [010/23] 2025-11-06 → 2025-11-20

(307 records)

    [011/23] 2025-11-20 → 2025-12-04

(301 records)

    [012/23] 2025-12-04 → 2025-12-18

(336 records)

    [013/23] 2025-12-18 → 2026-01-01

(334 records)

    [014/23] 2026-01-01 → 2026-01-15

(328 records)

    [015/23] 2026-01-15 → 2026-01-29

(321 records)

    [016/23] 2026-01-29 → 2026-02-12

(336 records)

    [017/23] 2026-02-12 → 2026-02-26

(336 records)

    [018/23] 2026-02-26 → 2026-03-12

(336 records)

    [019/23] 2026-03-12 → 2026-03-26

(336 records)

    [020/23] 2026-03-26 → 2026-04-09

(224 records)

    [021/23] 2026-04-09 → 2026-04-23

(336 records)

    [022/23] 2026-04-23 → 2026-05-07

(336 records)

    [023/23] 2026-05-07 → 2026-05-15

(164 records)

  no2 | sensor=13502162 | 23 windows
    [001/23] 2025-07-03 → 2025-07-17

(336 records)

    [002/23] 2025-07-17 → 2025-07-31

(289 records)

    [003/23] 2025-07-31 → 2025-08-14

(331 records)

    [004/23] 2025-08-14 → 2025-08-28

(224 records)

    [005/23] 2025-08-28 → 2025-09-11

(102 records)

    [006/23] 2025-09-11 → 2025-09-25

(336 records)

    [007/23] 2025-09-25 → 2025-10-09

(303 records)

    [008/23] 2025-10-09 → 2025-10-23

(319 records)

    [009/23] 2025-10-23 → 2025-11-06

(333 records)

    [010/23] 2025-11-06 → 2025-11-20

(330 records)

    [011/23] 2025-11-20 → 2025-12-04

(305 records)

    [012/23] 2025-12-04 → 2025-12-18

(207 records)

    [013/23] 2025-12-18 → 2026-01-01

(55 records)

    [014/23] 2026-01-01 → 2026-01-15

(315 records)

    [015/23] 2026-01-15 → 2026-01-29

(285 records)

    [016/23] 2026-01-29 → 2026-02-12

(327 records)

    [017/23] 2026-02-12 → 2026-02-26

(272 records)

    [018/23] 2026-02-26 → 2026-03-12

(295 records)

    [019/23] 2026-03-12 → 2026-03-26

(336 records)

    [020/23] 2026-03-26 → 2026-04-09

(316 records)

    [021/23] 2026-04-09 → 2026-04-23

(336 records)

    [022/23] 2026-04-23 → 2026-05-07

(336 records)

    [023/23] 2026-05-07 → 2026-05-15

(164 records)

  o3 | sensor=13502148 | 23 windows
    [001/23] 2025-07-03 → 2025-07-17

(336 records)

    [002/23] 2025-07-17 → 2025-07-31

(329 records)

    [003/23] 2025-07-31 → 2025-08-14

(332 records)

    [004/23] 2025-08-14 → 2025-08-28

(333 records)

    [005/23] 2025-08-28 → 2025-09-11

(334 records)

    [006/23] 2025-09-11 → 2025-09-25

(330 records)

    [007/23] 2025-09-25 → 2025-10-09

(294 records)

    [008/23] 2025-10-09 → 2025-10-23

(321 records)

    [009/23] 2025-10-23 → 2025-11-06

(321 records)

    [010/23] 2025-11-06 → 2025-11-20

(318 records)

    [011/23] 2025-11-20 → 2025-12-04

(305 records)

    [012/23] 2025-12-04 → 2025-12-18

(336 records)

    [013/23] 2025-12-18 → 2026-01-01

(156 records)

    [014/23] 2026-01-01 → 2026-01-15

(328 records)

    [015/23] 2026-01-15 → 2026-01-29

(321 records)

    [016/23] 2026-01-29 → 2026-02-12

(336 records)

    [017/23] 2026-02-12 → 2026-02-26

(336 records)

    [018/23] 2026-02-26 → 2026-03-12

(336 records)

    [019/23] 2026-03-12 → 2026-03-26

(336 records)

    [020/23] 2026-03-26 → 2026-04-09

(319 records)

    [021/23] 2026-04-09 → 2026-04-23

(336 records)

    [022/23] 2026-04-23 → 2026-05-07

(336 records)

    [023/23] 2026-05-07 → 2026-05-15

(164 records)

  pm25 | sensor=13502151 | 23 windows
    [001/23] 2025-07-03 → 2025-07-17

(336 records)

    [002/23] 2025-07-17 → 2025-07-31

(328 records)

    [003/23] 2025-07-31 → 2025-08-14

(332 records)

    [004/23] 2025-08-14 → 2025-08-28

(334 records)

    [005/23] 2025-08-28 → 2025-09-11

(328 records)

    [006/23] 2025-09-11 → 2025-09-25

(336 records)

    [007/23] 2025-09-25 → 2025-10-09

(311 records)

    [008/23] 2025-10-09 → 2025-10-23

(332 records)

    [009/23] 2025-10-23 → 2025-11-06

(319 records)

    [010/23] 2025-11-06 → 2025-11-20

(327 records)

    [011/23] 2025-11-20 → 2025-12-04

(305 records)

    [012/23] 2025-12-04 → 2025-12-18

(336 records)

    [013/23] 2025-12-18 → 2026-01-01

(332 records)

    [014/23] 2026-01-01 → 2026-01-15

(328 records)

    [015/23] 2026-01-15 → 2026-01-29

(321 records)

    [016/23] 2026-01-29 → 2026-02-12

(336 records)

    [017/23] 2026-02-12 → 2026-02-26

(336 records)

    [018/23] 2026-02-26 → 2026-03-12

(336 records)

    [019/23] 2026-03-12 → 2026-03-26

(336 records)

    [020/23] 2026-03-26 → 2026-04-09

(319 records)

    [021/23] 2026-04-09 → 2026-04-23

(336 records)

    [022/23] 2026-04-23 → 2026-05-07

(336 records)

    [023/23] 2026-05-07 → 2026-05-15

(164 records)

  so2 | sensor=13502157 | 23 windows
    [001/23] 2025-07-03 → 2025-07-17

(336 records)

    [002/23] 2025-07-17 → 2025-07-31

(329 records)

    [003/23] 2025-07-31 → 2025-08-14

(332 records)

    [004/23] 2025-08-14 → 2025-08-28

(326 records)

    [005/23] 2025-08-28 → 2025-09-11

(330 records)

    [006/23] 2025-09-11 → 2025-09-25

(308 records)

    [007/23] 2025-09-25 → 2025-10-09

(279 records)

    [008/23] 2025-10-09 → 2025-10-23

(331 records)

    [009/23] 2025-10-23 → 2025-11-06

(334 records)

    [010/23] 2025-11-06 → 2025-11-20

(330 records)

    [011/23] 2025-11-20 → 2025-12-04

(305 records)

    [012/23] 2025-12-04 → 2025-12-18

(336 records)

    [013/23] 2025-12-18 → 2026-01-01

(334 records)

    [014/23] 2026-01-01 → 2026-01-15

(328 records)

    [015/23] 2026-01-15 → 2026-01-29

(321 records)

    [016/23] 2026-01-29 → 2026-02-12

(336 records)

    [017/23] 2026-02-12 → 2026-02-26

(336 records)

    [018/23] 2026-02-26 → 2026-03-12

(336 records)

    [019/23] 2026-03-12 → 2026-03-26

(336 records)

    [020/23] 2026-03-26 → 2026-04-09

(319 records)

    [021/23] 2026-04-09 → 2026-04-23

(336 records)

    [022/23] 2026-04-23 → 2026-05-07

(334 records)

    [023/23] 2026-05-07 → 2026-05-15

(164 records)

  Saved: 4946812_Công viên Nhân Chính - Khuất Duy Tiến.csv  shape=(7434, 10)
  PM2.5 rows: 7404

============================================================
Station 4946813: Số 1 đường Giải Phóng - phường Bạch Mai - ĐHBK
  Range: 2021-01-01  →  2026-05-15

  Sensors: 5
  co | sensor=13502156 | 22 windows
    [001/22] 2025-07-03 → 2025-07-17

(336 records)

    [002/22] 2025-07-17 → 2025-07-31

(329 records)

    [003/22] 2025-07-31 → 2025-08-14

(332 records)

    [004/22] 2025-08-14 → 2025-08-28

(305 records)

    [005/22] 2025-08-28 → 2025-09-11

(331 records)

    [006/22] 2025-09-11 → 2025-09-25

(254 records)

    [007/22] 2025-09-25 → 2025-10-09

(270 records)

    [008/22] 2025-10-09 → 2025-10-23

(298 records)

    [009/22] 2025-10-23 → 2025-11-06

(145 records)

    [010/22] 2025-11-06 → 2025-11-20

(4 records)

    [011/22] 2025-11-20 → 2025-12-04

(0 records)

    [012/22] 2025-12-04 → 2025-12-18

(0 records)

    [013/22] 2025-12-18 → 2026-01-01

(0 records)

    [014/22] 2026-01-01 → 2026-01-15

(0 records)

    [015/22] 2026-01-15 → 2026-01-29

(0 records)

    [016/22] 2026-01-29 → 2026-02-12

(0 records)

    [017/22] 2026-02-12 → 2026-02-26

(0 records)

    [018/22] 2026-02-26 → 2026-03-12

(0 records)

    [019/22] 2026-03-12 → 2026-03-26

(0 records)

    [020/22] 2026-03-26 → 2026-04-09

(0 records)

    [021/22] 2026-04-09 → 2026-04-23

(0 records)

    [022/22] 2026-04-23 → 2026-04-24

(2 records)

  no2 | sensor=13502155 | 23 windows
    [001/23] 2025-07-03 → 2025-07-17

(336 records)

    [002/23] 2025-07-17 → 2025-07-31

(329 records)

    [003/23] 2025-07-31 → 2025-08-14

(331 records)

    [004/23] 2025-08-14 → 2025-08-28

(279 records)

    [005/23] 2025-08-28 → 2025-09-11

(196 records)

    [006/23] 2025-09-11 → 2025-09-25

(336 records)

    [007/23] 2025-09-25 → 2025-10-09

(311 records)

    [008/23] 2025-10-09 → 2025-10-23

(332 records)

    [009/23] 2025-10-23 → 2025-11-06

(335 records)

    [010/23] 2025-11-06 → 2025-11-20

(330 records)

    [011/23] 2025-11-20 → 2025-12-04

(305 records)

    [012/23] 2025-12-04 → 2025-12-18

(336 records)

    [013/23] 2025-12-18 → 2026-01-01

(336 records)

    [014/23] 2026-01-01 → 2026-01-15

(327 records)

    [015/23] 2026-01-15 → 2026-01-29

(321 records)

    [016/23] 2026-01-29 → 2026-02-12

(336 records)

    [017/23] 2026-02-12 → 2026-02-26

(336 records)

    [018/23] 2026-02-26 → 2026-03-12

(336 records)

    [019/23] 2026-03-12 → 2026-03-26

(336 records)

    [020/23] 2026-03-26 → 2026-04-09

(332 records)

    [021/23] 2026-04-09 → 2026-04-23

(336 records)

    [022/23] 2026-04-23 → 2026-05-07

(335 records)

    [023/23] 2026-05-07 → 2026-05-15

(164 records)

  o3 | sensor=13502149 | 23 windows
    [001/23] 2025-07-03 → 2025-07-17

(336 records)

    [002/23] 2025-07-17 → 2025-07-31

(328 records)

    [003/23] 2025-07-31 → 2025-08-14

(330 records)

    [004/23] 2025-08-14 → 2025-08-28

(301 records)

    [005/23] 2025-08-28 → 2025-09-11

(321 records)

    [006/23] 2025-09-11 → 2025-09-25

(335 records)

    [007/23] 2025-09-25 → 2025-10-09

(311 records)

    [008/23] 2025-10-09 → 2025-10-23

(332 records)

    [009/23] 2025-10-23 → 2025-11-06

(334 records)

    [010/23] 2025-11-06 → 2025-11-20

(330 records)

    [011/23] 2025-11-20 → 2025-12-04

(305 records)

    [012/23] 2025-12-04 → 2025-12-18

(336 records)

    [013/23] 2025-12-18 → 2026-01-01

(336 records)

    [014/23] 2026-01-01 → 2026-01-15

(291 records)

    [015/23] 2026-01-15 → 2026-01-29

(321 records)

    [016/23] 2026-01-29 → 2026-02-12

(336 records)

    [017/23] 2026-02-12 → 2026-02-26

(330 records)

    [018/23] 2026-02-26 → 2026-03-12

(212 records)

    [019/23] 2026-03-12 → 2026-03-26

(204 records)

    [020/23] 2026-03-26 → 2026-04-09

(332 records)

    [021/23] 2026-04-09 → 2026-04-23

(336 records)

    [022/23] 2026-04-23 → 2026-05-07

(336 records)

    [023/23] 2026-05-07 → 2026-05-15

(164 records)

  pm25 | sensor=13502154 | 23 windows
    [001/23] 2025-07-03 → 2025-07-17

(333 records)

    [002/23] 2025-07-17 → 2025-07-31

(320 records)

    [003/23] 2025-07-31 → 2025-08-14

(318 records)

    [004/23] 2025-08-14 → 2025-08-28

(245 records)

    [005/23] 2025-08-28 → 2025-09-11

(284 records)

    [006/23] 2025-09-11 → 2025-09-25

(335 records)

    [007/23] 2025-09-25 → 2025-10-09

(311 records)

    [008/23] 2025-10-09 → 2025-10-23

(332 records)

    [009/23] 2025-10-23 → 2025-11-06

(333 records)

    [010/23] 2025-11-06 → 2025-11-20

(323 records)

    [011/23] 2025-11-20 → 2025-12-04

(273 records)

    [012/23] 2025-12-04 → 2025-12-18

(334 records)

    [013/23] 2025-12-18 → 2026-01-01

(194 records)

    [014/23] 2026-01-01 → 2026-01-15

(320 records)

    [015/23] 2026-01-15 → 2026-01-29

(321 records)

    [016/23] 2026-01-29 → 2026-02-12

(331 records)

    [017/23] 2026-02-12 → 2026-02-26

(336 records)

    [018/23] 2026-02-26 → 2026-03-12

(336 records)

    [019/23] 2026-03-12 → 2026-03-26

(336 records)

    [020/23] 2026-03-26 → 2026-04-09

(332 records)

    [021/23] 2026-04-09 → 2026-04-23

(334 records)

    [022/23] 2026-04-23 → 2026-05-07

(331 records)

    [023/23] 2026-05-07 → 2026-05-15

(164 records)

  so2 | sensor=13502164 | 23 windows
    [001/23] 2025-07-03 → 2025-07-17

(336 records)

    [002/23] 2025-07-17 → 2025-07-31

(329 records)

    [003/23] 2025-07-31 → 2025-08-14

(321 records)

    [004/23] 2025-08-14 → 2025-08-28

(133 records)

    [005/23] 2025-08-28 → 2025-09-11

(258 records)

    [006/23] 2025-09-11 → 2025-09-25

(336 records)

    [007/23] 2025-09-25 → 2025-10-09

(311 records)

    [008/23] 2025-10-09 → 2025-10-23

(332 records)

    [009/23] 2025-10-23 → 2025-11-06

(335 records)

    [010/23] 2025-11-06 → 2025-11-20

(330 records)

    [011/23] 2025-11-20 → 2025-12-04

(305 records)

    [012/23] 2025-12-04 → 2025-12-18

(336 records)

    [013/23] 2025-12-18 → 2026-01-01

(336 records)

    [014/23] 2026-01-01 → 2026-01-15

(327 records)

    [015/23] 2026-01-15 → 2026-01-29

(194 records)

    [016/23] 2026-01-29 → 2026-02-12

(185 records)

    [017/23] 2026-02-12 → 2026-02-26

(336 records)

    [018/23] 2026-02-26 → 2026-03-12

(329 records)

    [019/23] 2026-03-12 → 2026-03-26

(18 records)

    [020/23] 2026-03-26 → 2026-04-09

(331 records)

    [021/23] 2026-04-09 → 2026-04-23

(336 records)

    [022/23] 2026-04-23 → 2026-05-07

(336 records)

    [023/23] 2026-05-07 → 2026-05-15

(164 records)

  Saved: 4946813_Số 1 đường Giải Phóng - phường Bạch Mai - ĐHBK.csv  shape=(7414, 10)
  PM2.5 rows: 7076

============================================================
Station 6123215: OceanPark
  Range: 2021-01-01  →  2026-05-15

  Sensors: 1
  pm25 | sensor=14581375 | 14 windows
    [001/14] 2025-11-08 → 2025-11-22

(316 records)

    [002/14] 2025-11-22 → 2025-12-06

(286 records)

    [003/14] 2025-12-06 → 2025-12-20

(335 records)

    [004/14] 2025-12-20 → 2026-01-03

(334 records)

    [005/14] 2026-01-03 → 2026-01-17

(335 records)

    [006/14] 2026-01-17 → 2026-01-31

(325 records)

    [007/14] 2026-01-31 → 2026-02-14

(336 records)

    [008/14] 2026-02-14 → 2026-02-28

(336 records)

    [009/14] 2026-02-28 → 2026-03-14

(336 records)

    [010/14] 2026-03-14 → 2026-03-28

(336 records)

    [011/14] 2026-03-28 → 2026-04-11

(336 records)

    [012/14] 2026-04-11 → 2026-04-25

(332 records)

    [013/14] 2026-04-25 → 2026-05-09

(335 records)

    [014/14] 2026-05-09 → 2026-05-15

(134 records)

  Saved: 6123215_OceanPark.csv  shape=(4412, 10)
  PM2.5 rows: 4412

============================================================

C:\Users\Admin\AppData\Local\Temp\ipykernel_28092\3028915927.py:97: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  pd.concat(all_station_dfs, ignore_index=True)

Combined: all_stations_crawled.csv  shape=(137669, 10)

,name,rows,pm25_valid,start,end
location_id,,,,,
7441,Hanoi,34051,30157,2021-01-01 01:00:00+00:00,2025-04-09 15:00:00+00:00
2161290,An Khánh,9430,9416,2024-01-29 07:00:00+00:00,2025-06-10 03:00:00+00:00
2161291,Cầu Diễn,1504,1497,2024-01-22 02:00:00+00:00,2024-12-11 14:00:00+00:00
2161292,"Số 46, phố Lưu Quang Vũ",16654,16003,2024-01-29 17:00:00+00:00,2026-05-15 00:00:00+00:00
2161293,Chúc Sơn,2933,2922,2024-01-09 22:00:00+00:00,2025-02-05 08:00:00+00:00
2161294,Cung thiếu nhi,3429,3418,2024-01-29 07:00:00+00:00,2025-02-05 03:00:00+00:00
2161295,Đầm Trấu,11,11,2024-01-29 07:00:00+00:00,2024-01-30 08:00:00+00:00
2161296,Đào Duy Từ,6086,6075,2024-01-15 08:00:00+00:00,2025-06-10 03:00:00+00:00
2161298,Đông Kinh Nghĩa Thục,852,852,2024-01-29 07:00:00+00:00,2024-04-15 09:00:00+00:00
2161299,Hàng Đậu,3275,3267,2024-01-29 08:00:00+00:00,2024-11-26 18:00:00+00:00
2161300,Hoàn Kiếm,22,22,2024-01-29 07:00:00+00:00,2024-01-31 23:00:00+00:00
2161301,Khương Trung,2538,2506,2024-01-29 07:00:00+00:00,2024-12-11 15:00:00+00:00
2161303,Kim Liên,566,472,2024-01-29 07:00:00+00:00,2024-03-22 06:00:00+00:00
2161304,Lê Trực,14,13,2024-01-29 07:00:00+00:00,2024-01-31 00:00:00+00:00
2161306,Minh Khai - Bắc Từ Liêm,9847,6792,2024-01-29 17:00:00+00:00,2026-05-15 00:00:00+00:00
2161307,Mỹ Đình,11,11,2024-01-28 23:00:00+00:00,2024-01-30 04:00:00+00:00
2161308,Phạm Văn Đồng,1,1,2024-01-22 08:00:00+00:00,2024-01-22 08:00:00+00:00
2161309,Pháp Vân,6837,6828,2024-01-29 07:00:00+00:00,2025-02-05 04:00:00+00:00
2161313,Tân Mai,303,280,2024-01-29 07:00:00+00:00,2024-03-01 04:00:00+00:00
2161314,Tây Hồ Tây,563,542,2024-01-29 07:00:00+00:00,2024-03-22 09:00:00+00:00
2161315,Tây Mỗ,52,51,2024-01-29 07:00:00+00:00,2024-02-07 00:00:00+00:00
2161316,Thành Công,220,220,2024-01-29 07:00:00+00:00,2024-02-27 00:00:00+00:00
2161318,Tứ Liên,574,550,2024-01-29 07:00:00+00:00,2024-03-22 04:00:00+00:00
2161320,Vân Hà,10546,10526,2024-01-29 16:00:00+00:00,2025-06-10 03:00:00+00:00
2161321,Văn Quán,761,758,2024-01-29 07:00:00+00:00,2024-04-05 00:00:00+00:00
2161322,Võng La,2,2,2024-01-15 08:00:00+00:00,2024-01-15 09:00:00+00:00
4946811,556 Nguyễn Văn Cừ,7327,7171,2025-07-03 16:00:00+00:00,2026-05-15 00:00:00+00:00
4946812,Công viên Nhân Chính - Khuất Duy Tiến,7434,7404,2025-07-03 16:00:00+00:00,2026-05-15 00:00:00+00:00
4946813,Số 1 đường Giải Phóng - phường Bạch Mai - ĐHBK,7414,7076,2025-07-03 16:00:00+00:00,2026-05-15 00:00:00+00:00
6123215,OceanPark,4412,4412,2025-11-08 07:00:00+00:00,2026-05-15 00:00:00+00:00

parameter_name,datetime_utc,location_id,location_name,latitude,longitude,CO mass µg/m³,NO₂ mass µg/m³,O₃ mass µg/m³,PM2.5 µg/m³,SO₂ mass µg/m³
0,2021-01-01 01:00:00+00:00,7441,Hanoi,21.021939,105.818806,NaN,NaN,NaN,70.0,NaN
1,2021-01-01 02:00:00+00:00,7441,Hanoi,21.021939,105.818806,NaN,NaN,NaN,81.0,NaN
2,2021-01-01 03:00:00+00:00,7441,Hanoi,21.021939,105.818806,NaN,NaN,NaN,49.0,NaN
3,2021-01-01 04:00:00+00:00,7441,Hanoi,21.021939,105.818806,NaN,NaN,NaN,50.0,NaN
4,2021-01-01 05:00:00+00:00,7441,Hanoi,21.021939,105.818806,NaN,NaN,NaN,50.0,NaN
5,2021-01-01 06:00:00+00:00,7441,Hanoi,21.021939,105.818806,NaN,NaN,NaN,56.0,NaN
6,2021-01-01 07:00:00+00:00,7441,Hanoi,21.021939,105.818806,NaN,NaN,NaN,46.0,NaN
7,2021-01-01 08:00:00+00:00,7441,Hanoi,21.021939,105.818806,NaN,NaN,NaN,46.0,NaN
8,2021-01-01 09:00:00+00:00,7441,Hanoi,21.021939,105.818806,NaN,NaN,NaN,46.0,NaN
9,2021-01-01 10:00:00+00:00,7441,Hanoi,21.021939,105.818806,NaN,NaN,NaN,49.0,NaN